package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class BusPoliza extends javax.swing.JFrame {
DefaultTableModel Poliza;
private TableRowSorter tr;
    /**
     * Creates new form BusPoliza
     */
    public BusPoliza() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    public void filtros() {
        int columnaABuscar = 0;
       
        if (cboBusPol.getSelectedItem() == "No. Póliza") {
            columnaABuscar = 0;
        }
        if (cboBusPol.getSelectedItem().toString() == "Día Emisión") {
            columnaABuscar = 1;
        }
        if (cboBusPol.getSelectedItem() == "Mes Emisión") {
            columnaABuscar = 2;
        }
        if (cboBusPol.getSelectedItem() == "Año Emisión") {
            columnaABuscar = 3;
        }
        if (cboBusPol.getSelectedItem().toString() == "Día Firma") {
            columnaABuscar = 4;
        }
        if (cboBusPol.getSelectedItem().toString() == "Mes Firma") {
            columnaABuscar = 5;
        }
        if (cboBusPol.getSelectedItem() == "Año Firma") {
            columnaABuscar = 6;
        }
         if (cboBusPol.getSelectedItem().toString() == "Día Vigencia") {
            columnaABuscar = 7;
        }
        if (cboBusPol.getSelectedItem().toString() == "Mes Vigencia") {
            columnaABuscar = 8;
        }
         if (cboBusPol.getSelectedItem() == "Año Vigencia") {
            columnaABuscar = 9;
        }
          if (cboBusPol.getSelectedItem() == "Cédula") {
            columnaABuscar = 10;
        }
        if (cboBusPol.getSelectedItem() == "Placa") {
            columnaABuscar = 11;
        }
        
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+txtBusPol.getText(), columnaABuscar));
    
      }
    void CargarTabla(String Solicitud)
    {
        try
        {
            String sSQL="";

            String[] Titulos = {"No. PÓLIZA", "DÍA EMISIÓN", "MES EMISIÓN", "AÑO EMISIÓN","DÍA FIRMA", "MES FIRMA", "AÑO FIRMA", "DÍA VIGENCIA", "MES  VIGENCIA", "AÑO  VIGENCIA", "CÉDULA", "PLACA","USUARIO REGISTRO"};
            String[] Datos = new String[13];

            Poliza = new DefaultTableModel(null,Titulos);
            //Integer.parseInt(Solicitud);
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT num_poliza, emi_d, emi_m, emi_a, fir_d, fir_m, fir_a, vig_d, vig_m, vig_a, nom_cli, num_pla,usuario_ingreso FROM poliza "
                    + "WHERE CONCAT(num_poliza) LIKE '%"+Solicitud+"%' ";
          

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Datos[0] = rs.getString("num_poliza");             
                Datos[1] = rs.getString("emi_d");
                Datos[2] = rs.getString("emi_m");
                Datos[3] = rs.getString("emi_a");
                Datos[4] = rs.getString("fir_d");
                Datos[5] = rs.getString("fir_m");
                Datos[6] = rs.getString("fir_a");
                Datos[7] = rs.getString("vig_d");
                Datos[8] = rs.getString("vig_m");
                Datos[9] = rs.getString("vig_a");
                Datos[10] = rs.getString("nom_cli");
                Datos[11] = rs.getString("num_pla");
                Datos[12] = rs.getString("usuario_ingreso");
                        
                       
                Poliza.addRow(Datos);
            }
            tblBusPol.setModel(Poliza);


        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    } 
        
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }
     void Borrar()
    {
            txtBusPol.setText("");
            
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoBusPol = new javax.swing.JLabel();
        lblTitBusPol = new javax.swing.JLabel();
        pnlBusPol = new javax.swing.JPanel();
        scpBusPol = new javax.swing.JScrollPane();
        tblBusPol = new javax.swing.JTable();
        btnBusBusPol = new javax.swing.JButton();
        btnSalBusPol = new javax.swing.JButton();
        lblNumBusPol = new javax.swing.JLabel();
        cboBusPol = new javax.swing.JComboBox<>();
        txtBusPol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmBusPoliza"); // NOI18N

        lblIconoBusPol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poliza.png"))); // NOI18N

        lblTitBusPol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitBusPol.setText("BUSCAR PÓLIZA");

        pnlBusPol.setBackground(new java.awt.Color(79, 157, 157));
        pnlBusPol.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Póliza"));

        tblBusPol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpBusPol.setViewportView(tblBusPol);

        btnBusBusPol.setBackground(new java.awt.Color(79, 157, 157));
        btnBusBusPol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnBusBusPol.setText("MOSTRAR DATOS");
        btnBusBusPol.setMaximumSize(new java.awt.Dimension(109, 33));
        btnBusBusPol.setMinimumSize(new java.awt.Dimension(109, 33));
        btnBusBusPol.setPreferredSize(new java.awt.Dimension(109, 33));
        btnBusBusPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusBusPolActionPerformed(evt);
            }
        });

        btnSalBusPol.setBackground(new java.awt.Color(79, 157, 157));
        btnSalBusPol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalBusPol.setText("SALIR");
        btnSalBusPol.setMaximumSize(new java.awt.Dimension(109, 33));
        btnSalBusPol.setMinimumSize(new java.awt.Dimension(109, 33));
        btnSalBusPol.setPreferredSize(new java.awt.Dimension(109, 33));
        btnSalBusPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalBusPolActionPerformed(evt);
            }
        });

        lblNumBusPol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumBusPol.setText("Seleccione Para Buscar Póliza");

        cboBusPol.setBackground(new java.awt.Color(79, 157, 157));
        cboBusPol.setMaximumRowCount(13);
        cboBusPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "No. Póliza", "Día Emisión", "Mes Emisión", "Año Emisión", "Día Firma", "Mes Firma", "Año Firma", "Día Vigencia", "Mes Vigencia", "Año Vigencia", "Cédula", "Placa", " " }));
        cboBusPol.setToolTipText("Seleccionar");
        cboBusPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBusPolActionPerformed(evt);
            }
        });

        txtBusPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusPolActionPerformed(evt);
            }
        });
        txtBusPol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusPolKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlBusPolLayout = new javax.swing.GroupLayout(pnlBusPol);
        pnlBusPol.setLayout(pnlBusPolLayout);
        pnlBusPolLayout.setHorizontalGroup(
            pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusPolLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpBusPol, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addGroup(pnlBusPolLayout.createSequentialGroup()
                        .addComponent(lblNumBusPol)
                        .addGap(36, 36, 36)
                        .addComponent(cboBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnBusBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBusPolLayout.setVerticalGroup(
            pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusPolLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBusBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBusPolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNumBusPol))
                .addGap(16, 16, 16)
                .addComponent(scpBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoBusPol)
                        .addGap(321, 321, 321)
                        .addComponent(lblTitBusPol)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlBusPol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoBusPol))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblTitBusPol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBusPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusBusPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusBusPolActionPerformed
        // TODO add your handling code here:
        String Solicitud = txtBusPol.getText();
        if(ValidarNum(Solicitud)==false){
            JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
        }
        else{
            Borrar();
            CargarTabla(Solicitud);
            
        }
    }//GEN-LAST:event_btnBusBusPolActionPerformed

    private void btnSalBusPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalBusPolActionPerformed
        // TODO add your handling code here:
        this.dispose();
       
    }//GEN-LAST:event_btnSalBusPolActionPerformed

    private void cboBusPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBusPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBusPolActionPerformed

    private void txtBusPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusPolActionPerformed

    private void txtBusPolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusPolKeyTyped
        // TODO add your handling code here:
        txtBusPol.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusPol.getText()).trim();
                txtBusPol.setText(cadena);
                repaint();
                filtros();
            }
        });
        tr = new TableRowSorter(tblBusPol.getModel());
        tblBusPol.setRowSorter(tr);
    }//GEN-LAST:event_txtBusPolKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusPoliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusBusPol;
    private javax.swing.JButton btnSalBusPol;
    private javax.swing.JComboBox<String> cboBusPol;
    private javax.swing.JLabel lblIconoBusPol;
    private javax.swing.JLabel lblNumBusPol;
    private javax.swing.JLabel lblTitBusPol;
    private javax.swing.JPanel pnlBusPol;
    private javax.swing.JScrollPane scpBusPol;
    private javax.swing.JTable tblBusPol;
    private javax.swing.JTextField txtBusPol;
    // End of variables declaration//GEN-END:variables
}
