/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.ConexionMySQL;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.IndexedColors;

/**
 *
 * @author Richard
 */
public class ConProducto extends javax.swing.JFrame {
DefaultTableModel modelo;
    private ConexionMySQL cl = new ConexionMySQL();
    private Connection cn = cl.Conectar();
    private TableRowSorter tr;
    /**
     * Creates new form ConProducto
     */
    public ConProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        //setListar(Object Informacion);
        String Cliente = lblExpConPro.getText();
        setListar(modelo); 
    }
    
    public void filtros() {
        int columnaABuscar = 0;
  
        if (cboExpConPro.getSelectedItem() == "Cédula") {
            columnaABuscar = 0;
        }
        if (cboExpConPro.getSelectedItem() == "Tipo") {
            columnaABuscar = 2;
        }
        if (cboExpConPro.getSelectedItem().toString() == "Marca") {
            columnaABuscar = 3;
        }
        if (cboExpConPro.getSelectedItem().toString() == "Modelo") {
            columnaABuscar = 4;
        }
        if (cboExpConPro.getSelectedItem() == "Año") {
            columnaABuscar = 5;
        }
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+txtExpConPro.getText(), columnaABuscar));
    
      }
    
    public void setListar(Object Informacion) {
        DefaultTableModel modelo = (DefaultTableModel) this.tblExpConPro.getModel();
        

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        String sql = "SELECT * FROM vehiculo";
        Object Datos[]= new Object[11];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Datos[0] = rs.getString("nom_pro");
                Datos[1] = rs.getString("matri_vehi");
                Datos[2] = rs.getString("tip");
                Datos[3] = rs.getString("mar");
                Datos[4] = rs.getString("modelo");
                Datos[5] = rs.getString("anio");
                Datos[6] = rs.getString("col");
                Datos[7] = rs.getString("val");
                modelo.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   
     private boolean getFileExtension(File file) {
        String ext = null;
        String s = file.getName();
        int i = s.lastIndexOf('.');

        if (i > 0 && i < s.length() - 1) {
            ext = s.substring(i + 1).toLowerCase();
        }

        if (ext != null) {
            return true;
        } else {
            return false;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoFecRep = new javax.swing.JLabel();
        scpConSol = new javax.swing.JScrollPane();
        tblExpConPro = new javax.swing.JTable();
        btnExpConPro = new javax.swing.JButton();
        btnSalExpConPro = new javax.swing.JButton();
        lblExpConPro = new javax.swing.JLabel();
        cboExpConPro = new javax.swing.JComboBox<>();
        txtExpConPro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIconoFecRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N

        tblExpConPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÉDULA", "PLACA", "TIPO", "MARCA", "MODELO", "AÑO", "COLOR", "VALOR ACTUAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExpConPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scpConSol.setViewportView(tblExpConPro);

        btnExpConPro.setBackground(new java.awt.Color(79, 157, 157));
        btnExpConPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExpConPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exportar.png"))); // NOI18N
        btnExpConPro.setText(" EXPORTAR EXCEL");
        btnExpConPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExpConPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpConProActionPerformed(evt);
            }
        });

        btnSalExpConPro.setBackground(new java.awt.Color(79, 157, 157));
        btnSalExpConPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalExpConPro.setText("SALIR");
        btnSalExpConPro.setMaximumSize(new java.awt.Dimension(157, 33));
        btnSalExpConPro.setMinimumSize(new java.awt.Dimension(157, 33));
        btnSalExpConPro.setPreferredSize(new java.awt.Dimension(157, 33));
        btnSalExpConPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalExpConProActionPerformed(evt);
            }
        });

        lblExpConPro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblExpConPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpConPro.setText("CONSULTA PRODUCTOS");

        cboExpConPro.setBackground(new java.awt.Color(79, 157, 157));
        cboExpConPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Cédula", "Tipo", "Marca", "Modelo", "Año" }));
        cboExpConPro.setToolTipText("Seleccionar");
        cboExpConPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboExpConProActionPerformed(evt);
            }
        });

        txtExpConPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpConProActionPerformed(evt);
            }
        });
        txtExpConPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExpConProKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpConSol, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIconoFecRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnExpConPro)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconoFecRep)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalExpConPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31)
                .addComponent(scpConSol, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpConProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpConProActionPerformed
        //generarExcel();
        try{
            Thread t=new Thread(){
                public void run (){

                HSSFWorkbook workbook = new HSSFWorkbook();
                HSSFSheet hoja = workbook.createSheet();
                CellStyle style = workbook.createCellStyle();
                style.setFillForegroundColor(IndexedColors.LIGHT_TURQUOISE.getIndex());
                style.setFillPattern(CellStyle.SOLID_FOREGROUND);
                
                style.setBorderTop(CellStyle.BORDER_THIN);
                style.setBorderLeft(CellStyle.BORDER_THIN);
            	style.setBorderRight(CellStyle.BORDER_THIN);
		style.setBorderBottom(CellStyle.BORDER_THIN);
                   
                //style.
                String[] titulos = {"CÉDULA" ,"PLACA", "TIPO", "MARCA", "MODELO",
                            "AÑO", "COLOR","VALOR ACTUAL"};
                HSSFRow fila = hoja.createRow(0);
                 // Creamos el encabezado
                for(int i = 0; i < titulos.length; i++) {
                 // Creamos una celda en esa fila, en la posicion 
                 // indicada por el contador del ciclo
                Cell celda = fila.createCell(i);
                celda.setCellStyle(style); 
                celda.setCellValue(titulos[i]);
                }
                    
                    HSSFRow filas;
                    Rectangle rect;
                    for(int i=0; i<tblExpConPro.getRowCount();i++){
                        rect = tblExpConPro.getCellRect(i, 0, true);
                        try
                        {
                            tblExpConPro.scrollRectToVisible(rect);
                        }catch(java.lang.ClassCastException e){}
                        tblExpConPro.setRowSelectionInterval(i, i);
                        
                        filas = hoja.createRow((i+1));
                                                
                        filas.createCell(0).setCellValue(tblExpConPro.getValueAt(i, 0).toString());
                        filas.createCell(1).setCellValue(tblExpConPro.getValueAt(i, 1).toString());
                        filas.createCell(2).setCellValue(tblExpConPro.getValueAt(i, 2).toString());
                        filas.createCell(3).setCellValue(tblExpConPro.getValueAt(i, 3).toString());
                        filas.createCell(4).setCellValue(tblExpConPro.getValueAt(i, 4).toString());
                        filas.createCell(5).setCellValue(tblExpConPro.getValueAt(i, 5).toString());
                        filas.createCell(6).setCellValue(tblExpConPro.getValueAt(i, 6).toString());
                        filas.createCell(7).setCellValue(tblExpConPro.getValueAt(i, 7).toString());
                        
                    }
                    JFileChooser fileChooser = new JFileChooser();
                    FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xls)", "xls");
                    fileChooser.setAcceptAllFileFilterUsed(false);
                    fileChooser.setFileFilter(filter);
                    fileChooser.setDialogTitle("GUARDAR ARCHIVO");
                    if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
        
                    {

                        try {
                            File archivo = new File(fileChooser.getSelectedFile().getAbsolutePath());

                            OutputStream out = null;
                            if (getFileExtension(archivo)) {
                                out = new FileOutputStream(fileChooser.getSelectedFile().getAbsolutePath());
                            } else {
                                out = new FileOutputStream(fileChooser.getSelectedFile().getAbsolutePath() + ".xls");
                            }

                            JOptionPane.showMessageDialog(null, "Archivo generado con éxito");

                            workbook.write(out);
                            workbook.close();
                            out.flush();
                            out.close();
                        } catch (IOException ex) {
                            Logger.getLogger(ConSolicitud.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

        
            };
            t.start();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_btnExpConProActionPerformed

    private void btnSalExpConProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalExpConProActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalExpConProActionPerformed

    private void cboExpConProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboExpConProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboExpConProActionPerformed

    private void txtExpConProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpConProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpConProActionPerformed

    private void txtExpConProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpConProKeyTyped
        // TODO add your handling code here:
        txtExpConPro.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {
                String cadena = (txtExpConPro.getText()).trim();
                txtExpConPro.setText(cadena);
                repaint();
                filtros();
            }
        });
        tr = new TableRowSorter(tblExpConPro.getModel());
        tblExpConPro.setRowSorter(tr);
    }//GEN-LAST:event_txtExpConProKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpConPro;
    private javax.swing.JButton btnSalExpConPro;
    private javax.swing.JComboBox<String> cboExpConPro;
    private javax.swing.JLabel lblExpConPro;
    private javax.swing.JLabel lblIconoFecRep;
    private javax.swing.JScrollPane scpConSol;
    private javax.swing.JTable tblExpConPro;
    private javax.swing.JTextField txtExpConPro;
    // End of variables declaration//GEN-END:variables
}
