package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class EliAseguradora extends javax.swing.JFrame {
    DefaultTableModel tabla;

    /**
     * Creates new form EliAseguradoras
     */
    public EliAseguradora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    void CargarTabla(String datos)
    {
        String[] Titulos = {"CÓDIGO" ,"NOMBRE", "CIUDAD", "DIRECCIÓN", "GERENTE","TELÉFONO", "E-MAIL"};
        String[] Informacion = new String[7];

        String sSQL="";

        tabla = new DefaultTableModel(null,Titulos);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();

        sSQL = "SELECT cod_emp, nom_emp, ciu, dir, ger, telf, mail FROM aseguradora " +
                "WHERE CONCAT(cod_emp) LIKE '%"+datos+"%'";

        try
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Informacion[0] = rs.getString("cod_emp");
                Informacion[1] = rs.getString("nom_emp");
                Informacion[2] = rs.getString("ciu");
                Informacion[3] = rs.getString("dir");
                Informacion[4] = rs.getString("ger");
                Informacion[5] = rs.getString("telf");
                Informacion[6] = rs.getString("mail");

                tabla.addRow(Informacion);
            }
            tblEliAse.setModel(tabla);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoEliAse = new javax.swing.JLabel();
        lblTituloEliAse = new javax.swing.JLabel();
        pnlMostrarEliAse = new javax.swing.JPanel();
        btnEliAse = new javax.swing.JButton();
        scpMosEliAse = new javax.swing.JScrollPane();
        tblEliAse = new javax.swing.JTable();
        btnMosEliAse = new javax.swing.JButton();
        btnSalirEliAse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmEliAseguradoras"); // NOI18N

        lblIconoEliAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empresa.png"))); // NOI18N

        lblTituloEliAse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloEliAse.setText("ELIMINAR ASEGURADORA");

        pnlMostrarEliAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlMostrarEliAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestor Eliminar"));

        btnEliAse.setBackground(new java.awt.Color(79, 157, 157));
        btnEliAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btnEliAse.setText("ELIMINAR");
        btnEliAse.setMaximumSize(new java.awt.Dimension(147, 33));
        btnEliAse.setMinimumSize(new java.awt.Dimension(147, 33));
        btnEliAse.setPreferredSize(new java.awt.Dimension(147, 33));
        btnEliAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliAseActionPerformed(evt);
            }
        });

        tblEliAse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpMosEliAse.setViewportView(tblEliAse);

        btnMosEliAse.setBackground(new java.awt.Color(79, 157, 157));
        btnMosEliAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnMosEliAse.setText("MOSTRAR DATOS");
        btnMosEliAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosEliAseActionPerformed(evt);
            }
        });

        btnSalirEliAse.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirEliAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirEliAse.setText("SALIR");
        btnSalirEliAse.setMaximumSize(new java.awt.Dimension(147, 33));
        btnSalirEliAse.setMinimumSize(new java.awt.Dimension(147, 33));
        btnSalirEliAse.setPreferredSize(new java.awt.Dimension(147, 33));
        btnSalirEliAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEliAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMostrarEliAseLayout = new javax.swing.GroupLayout(pnlMostrarEliAse);
        pnlMostrarEliAse.setLayout(pnlMostrarEliAseLayout);
        pnlMostrarEliAseLayout.setHorizontalGroup(
            pnlMostrarEliAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarEliAseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMostrarEliAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpMosEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMostrarEliAseLayout.createSequentialGroup()
                        .addComponent(btnMosEliAse)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalirEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMostrarEliAseLayout.setVerticalGroup(
            pnlMostrarEliAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarEliAseLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlMostrarEliAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMosEliAse))
                .addGap(11, 11, 11)
                .addComponent(scpMosEliAse, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(lblTituloEliAse))
                    .addComponent(pnlMostrarEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTituloEliAse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMostrarEliAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliAseActionPerformed
        // TODO add your handling code here:
       
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        int fila= tblEliAse.getSelectedRow();
        if(fila<0)
            {
             JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
            }
        else
        {
            int Pregunta;
            Pregunta = JOptionPane.showConfirmDialog(null,"Desea Eliminar Los Datos","Pregunta" ,0);
            if (Pregunta==0)
            {
                idfila= tblEliAse.getValueAt(fila, 0).toString();
                String eli="DELETE FROM aseguradora WHERE cod_emp = '"+idfila+"'";
                PreparedStatement pst;
                try
                {
                    pst = cn.prepareStatement(eli);
                    int m=pst.executeUpdate();
                    if(m>0)
                    {
                        JOptionPane.showMessageDialog(this, "ELIMINO LOS DATOS DE FORMA CORRECTA");
                        String Informacion = lblIconoEliAse.getText();
                        CargarTabla(Informacion);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                        String Informacion = lblIconoEliAse.getText();
                        CargarTabla(Informacion);
                    }
                
                } catch (SQLException ex) 
                {
                    Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                 try
                    {
                        String sSQL="";

                        sSQL = "DELETE FROM proforma WHERE cod_emp = '"+idfila+"'";
                        Statement st = cn.createStatement();
                        st.execute(sSQL);
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
            }
        }
    }//GEN-LAST:event_btnEliAseActionPerformed

    private void btnMosEliAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosEliAseActionPerformed
        // TODO add your handling code here:
        String datos = lblIconoEliAse.getText();
        CargarTabla(datos);

    }//GEN-LAST:event_btnMosEliAseActionPerformed

    private void btnSalirEliAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEliAseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario MenuUsuarioJF = new MenuUsuario();
        //MenuUsuarioJF.setVisible(true);
    }//GEN-LAST:event_btnSalirEliAseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliAseguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliAse;
    private javax.swing.JButton btnMosEliAse;
    private javax.swing.JButton btnSalirEliAse;
    private javax.swing.JLabel lblIconoEliAse;
    private javax.swing.JLabel lblTituloEliAse;
    private javax.swing.JPanel pnlMostrarEliAse;
    private javax.swing.JScrollPane scpMosEliAse;
    private javax.swing.JTable tblEliAse;
    // End of variables declaration//GEN-END:variables
String idfila="";
}
