package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class EliCliente extends javax.swing.JFrame {
DefaultTableModel Cliente;
    /**
     * Creates new form EliCliente
     */
    public EliCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    void CargarTabla(Object Informacion)
    {
        try
        {
            String sSQL="";
            String[] Titulos = {"CÉDULA", "PRI. NOMBRE", "SEG. NOMBBRE", "PRI. APELLIDO", "SEG. APELLIDO", "FECHA NACIMIENTO", "GÉNERO", "TELÉFONO", "CIUDAD", "DIRECCIÓN", "MAIL"};
            //Object[] Datos = new Object[9];
            Object Datos[]= new Object[11];
            
            Cliente = new DefaultTableModel(null,Titulos);

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT ci_cli, pnom_cli, snom_cli, pape_cli, sape_cli, fec_nac, gen, telf, ciu, dir, mail FROM cliente "
                    + "WHERE CONCAT(ci_cli) LIKE '%"+Informacion+"%'";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                        Datos[0] = rs.getString("ci_cli");
                        Datos[1] = rs.getString("pnom_cli");
                        Datos[2] = rs.getString("snom_cli");
                        Datos[3] = rs.getString("pape_cli");
                        Datos[4] = rs.getString("sape_cli");
                        Datos[5] = rs.getDate("fec_nac");
                        Datos[6] = rs.getString("gen");
                        Datos[7] = rs.getString("telf");
                        Datos[8] = rs.getString("ciu");
                        Datos[9] = rs.getString("dir");
                        Datos[10] = rs.getString("mail");                     

                        Cliente.addRow(Datos);
            }
            tblEliCli.setModel(Cliente);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoEliCli = new javax.swing.JLabel();
        lblTituloEliCli = new javax.swing.JLabel();
        pnlMosEliCli = new javax.swing.JPanel();
        scpEliCli = new javax.swing.JScrollPane();
        tblEliCli = new javax.swing.JTable();
        btnMosEliCli = new javax.swing.JButton();
        btnEliminarEliCli = new javax.swing.JButton();
        btnSalirEliCli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmEliCliente"); // NOI18N

        lblIconoEliCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N

        lblTituloEliCli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloEliCli.setText("ELIMINAR CLIENTE");

        pnlMosEliCli.setBackground(new java.awt.Color(79, 157, 157));
        pnlMosEliCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestor de Eliminación"));

        tblEliCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpEliCli.setViewportView(tblEliCli);

        btnMosEliCli.setBackground(new java.awt.Color(79, 157, 157));
        btnMosEliCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnMosEliCli.setText("MOSTRAR DATOS");
        btnMosEliCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosEliCliActionPerformed(evt);
            }
        });

        btnEliminarEliCli.setBackground(new java.awt.Color(79, 157, 157));
        btnEliminarEliCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btnEliminarEliCli.setText("ELIMINAR");
        btnEliminarEliCli.setMaximumSize(new java.awt.Dimension(147, 33));
        btnEliminarEliCli.setMinimumSize(new java.awt.Dimension(147, 33));
        btnEliminarEliCli.setPreferredSize(new java.awt.Dimension(147, 33));
        btnEliminarEliCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEliCliActionPerformed(evt);
            }
        });

        btnSalirEliCli.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirEliCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirEliCli.setText("SALIR");
        btnSalirEliCli.setMaximumSize(new java.awt.Dimension(147, 33));
        btnSalirEliCli.setMinimumSize(new java.awt.Dimension(147, 33));
        btnSalirEliCli.setPreferredSize(new java.awt.Dimension(147, 33));
        btnSalirEliCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEliCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMosEliCliLayout = new javax.swing.GroupLayout(pnlMosEliCli);
        pnlMosEliCli.setLayout(pnlMosEliCliLayout);
        pnlMosEliCliLayout.setHorizontalGroup(
            pnlMosEliCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMosEliCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpEliCli)
                    .addGroup(pnlMosEliCliLayout.createSequentialGroup()
                        .addComponent(btnMosEliCli)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminarEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalirEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 686, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMosEliCliLayout.setVerticalGroup(
            pnlMosEliCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliCliLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlMosEliCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMosEliCli))
                .addGap(11, 11, 11)
                .addComponent(scpEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMosEliCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoEliCli)
                        .addGap(421, 421, 421)
                        .addComponent(lblTituloEliCli)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIconoEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTituloEliCli)))
                .addGap(5, 5, 5)
                .addComponent(pnlMosEliCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMosEliCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosEliCliActionPerformed
        // TODO add your handling code here:
        String Cliente = lblIconoEliCli.getText();
        CargarTabla(Cliente);
    }//GEN-LAST:event_btnMosEliCliActionPerformed

    private void btnEliminarEliCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEliCliActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        int fila= tblEliCli.getSelectedRow();
        if(fila<0)
            {
             JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
            }
        else
        {
            int Pregunta;
            Pregunta = JOptionPane.showConfirmDialog(null,"Desea Eliminar Los Datos","Pregunta" ,0);
            if (Pregunta==0)
            {
                idfila= tblEliCli.getValueAt(fila, 0).toString();
                String eli="DELETE FROM cliente WHERE ci_cli = '"+idfila+"'";
                PreparedStatement pst;
                try
                {
                    pst = cn.prepareStatement(eli);
                    int m=pst.executeUpdate();
                    if(m>0)
                    {
                        JOptionPane.showMessageDialog(this, "ELIMINO LOS DATOS DE FORMA CORRECTA");
                        String Cliente = lblIconoEliCli.getText();
                        CargarTabla(Cliente);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                        //CargarTabla();
                    }
                
                } catch (SQLException ex) 
                {
                    Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarEliCliActionPerformed

    private void btnSalirEliCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEliCliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario clienteJF = new MenuUsuario();
        //clienteJF.setVisible(true);
    }//GEN-LAST:event_btnSalirEliCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEliCli;
    private javax.swing.JButton btnMosEliCli;
    private javax.swing.JButton btnSalirEliCli;
    private javax.swing.JLabel lblIconoEliCli;
    private javax.swing.JLabel lblTituloEliCli;
    private javax.swing.JPanel pnlMosEliCli;
    private javax.swing.JScrollPane scpEliCli;
    private javax.swing.JTable tblEliCli;
    // End of variables declaration//GEN-END:variables
String idfila="";
}
