package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class EliEmpleado extends javax.swing.JFrame {
DefaultTableModel Empleado;
    /**
     * Creates new form EliEmpleado
     */
    public EliEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    void CargarTabla(Object Informacion)
    {
        try
        {
            String sSQL="";
            String[] Titulos = {"CÉDULA", "PRI. NOMBRE", "SEG. NOMBBRE", "PRI. APELLIDO", "SEG. APELLIDO", "FECHA NACIMIENTO", "GÉNERO", "TELÉFONO", "CIUDAD", "DIRECCIÓN", "MAIL"};
            //Object[] Datos = new Object[9];
            Object Datos[]= new Object[11];
            
            Empleado = new DefaultTableModel(null,Titulos);

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT ci_emp, pnom_emp, snom_emp, pape_emp, sape_emp, fec_nac, gen, telf, ciu, dir, mail FROM empleado "
                    + "WHERE CONCAT(ci_emp) LIKE '%"+Informacion+"%'";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                        Datos[0] = rs.getString("ci_emp");
                        Datos[1] = rs.getString("pnom_emp");
                        Datos[2] = rs.getString("snom_emp");
                        Datos[3] = rs.getString("pape_emp");
                        Datos[4] = rs.getString("sape_emp");
                        Datos[5] = rs.getDate("fec_nac");
                        Datos[6] = rs.getString("gen");
                        Datos[7] = rs.getString("telf");
                        Datos[8] = rs.getString("ciu");
                        Datos[9] = rs.getString("dir");
                        Datos[10] = rs.getString("mail");                     

                        Empleado.addRow(Datos);
            }
            tblEliEmp.setModel(Empleado);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitEliEmp = new javax.swing.JLabel();
        lblIconoEliEmp = new javax.swing.JLabel();
        pnlMosEliEmp = new javax.swing.JPanel();
        btnEliEliEmp = new javax.swing.JButton();
        btnSalEliEmp = new javax.swing.JButton();
        btnMosEliEmp = new javax.swing.JButton();
        scpEliEmp = new javax.swing.JScrollPane();
        tblEliEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");

        lblTitEliEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitEliEmp.setText("ELIMINAR EMPLEADO");

        lblIconoEliEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N

        pnlMosEliEmp.setBackground(new java.awt.Color(79, 157, 157));
        pnlMosEliEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestor de Eliminación"));

        btnEliEliEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnEliEliEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btnEliEliEmp.setText("ELIMINAR");
        btnEliEliEmp.setMaximumSize(new java.awt.Dimension(147, 33));
        btnEliEliEmp.setMinimumSize(new java.awt.Dimension(147, 33));
        btnEliEliEmp.setPreferredSize(new java.awt.Dimension(147, 33));
        btnEliEliEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliEliEmpActionPerformed(evt);
            }
        });

        btnSalEliEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnSalEliEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalEliEmp.setText("SALIR");
        btnSalEliEmp.setMaximumSize(new java.awt.Dimension(147, 33));
        btnSalEliEmp.setMinimumSize(new java.awt.Dimension(147, 33));
        btnSalEliEmp.setPreferredSize(new java.awt.Dimension(147, 33));
        btnSalEliEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalEliEmpActionPerformed(evt);
            }
        });

        btnMosEliEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnMosEliEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnMosEliEmp.setText("MOSTRAR DATOS");
        btnMosEliEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosEliEmpActionPerformed(evt);
            }
        });

        tblEliEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpEliEmp.setViewportView(tblEliEmp);

        javax.swing.GroupLayout pnlMosEliEmpLayout = new javax.swing.GroupLayout(pnlMosEliEmp);
        pnlMosEliEmp.setLayout(pnlMosEliEmpLayout);
        pnlMosEliEmpLayout.setHorizontalGroup(
            pnlMosEliEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMosEliEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpEliEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
                    .addGroup(pnlMosEliEmpLayout.createSequentialGroup()
                        .addComponent(btnMosEliEmp)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 767, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMosEliEmpLayout.setVerticalGroup(
            pnlMosEliEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliEmpLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlMosEliEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMosEliEmp))
                .addGap(11, 11, 11)
                .addComponent(scpEliEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoEliEmp)
                        .addGap(410, 410, 410)
                        .addComponent(lblTitEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMosEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIconoEliEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTitEliEmp)))
                .addGap(5, 5, 5)
                .addComponent(pnlMosEliEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliEliEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliEliEmpActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        int fila= tblEliEmp.getSelectedRow();
        if(fila<0)
            {
             JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
            }
        else
        {
            int Pregunta;
            Pregunta = JOptionPane.showConfirmDialog(null,"Desea Eliminar Los Datos","Pregunta" ,0);
            if (Pregunta==0)
            {
                idfila= tblEliEmp.getValueAt(fila, 0).toString();
                String eli="DELETE FROM empleado WHERE ci_emp = '"+idfila+"'";
                PreparedStatement pst;
                try
                {
                    pst = cn.prepareStatement(eli);
                    int m=pst.executeUpdate();
                    if(m>0)
                    {
                        JOptionPane.showMessageDialog(this, "ELIMINO LOS DATOS DE FORMA CORRECTA");
                        String Empleado = lblIconoEliEmp.getText();
                        CargarTabla(Empleado);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                        
                    }
                
                } catch (SQLException ex) 
                {
                    Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEliEliEmpActionPerformed

    private void btnSalEliEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalEliEmpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario MenuUsuarioJF = new MenuUsuario();
        //MenuUsuarioJF.setVisible(true);
    }//GEN-LAST:event_btnSalEliEmpActionPerformed

    private void btnMosEliEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosEliEmpActionPerformed
        // TODO add your handling code here:
        String Empleado = lblIconoEliEmp.getText();
        CargarTabla(Empleado);
    }//GEN-LAST:event_btnMosEliEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliEliEmp;
    private javax.swing.JButton btnMosEliEmp;
    private javax.swing.JButton btnSalEliEmp;
    private javax.swing.JLabel lblIconoEliEmp;
    private javax.swing.JLabel lblTitEliEmp;
    private javax.swing.JPanel pnlMosEliEmp;
    private javax.swing.JScrollPane scpEliEmp;
    private javax.swing.JTable tblEliEmp;
    // End of variables declaration//GEN-END:variables
String idfila="";
}
