package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class EliProducto extends javax.swing.JFrame {
DefaultTableModel Producto;
    /**
     * Creates new form EliProducto
     */
    public EliProducto() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    void CargarTabla(String Informaion)
    {
        
        String[] Titulos = {"PLACA", "TIPO", "MARCA", "MODELO", "AÑO", "COLOR", "VALOR"};
        Producto=new  DefaultTableModel(null,Titulos);  
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        String Datos [] = new String[7];
        String sql="SELECT * FROM  vehiculo"; 
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                Datos[0] = rs.getString("matri_vehi");
                Datos[1] = rs.getString("tip");
                Datos[2] = rs.getString("mar");
                Datos[3] = rs.getString("modelo");
                Datos[4] = rs.getString("anio");
                Datos[5] = rs.getString("col");
                Datos[6] = rs.getString("val");

                Producto.addRow(Datos);
            }
            tblEliPro.setModel(Producto);
        } catch (SQLException ex) {
            Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitEliPro = new javax.swing.JLabel();
        pnlMosEliPro = new javax.swing.JPanel();
        btnMosEliPro = new javax.swing.JButton();
        btnEliEliPro = new javax.swing.JButton();
        btnSalEliPro = new javax.swing.JButton();
        scpMosEliPro = new javax.swing.JScrollPane();
        tblEliPro = new javax.swing.JTable();
        lblIconoEliPro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");

        lblTitEliPro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitEliPro.setText("ELIMINAR VEHÍCULO");

        pnlMosEliPro.setBackground(new java.awt.Color(79, 157, 157));
        pnlMosEliPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestor de Eliminación"));

        btnMosEliPro.setBackground(new java.awt.Color(79, 157, 157));
        btnMosEliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnMosEliPro.setText("MOSTRAR DATOS");
        btnMosEliPro.setToolTipText("");
        btnMosEliPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosEliProActionPerformed(evt);
            }
        });

        btnEliEliPro.setBackground(new java.awt.Color(79, 157, 157));
        btnEliEliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btnEliEliPro.setText("ELIMINAR");
        btnEliEliPro.setMaximumSize(new java.awt.Dimension(147, 33));
        btnEliEliPro.setMinimumSize(new java.awt.Dimension(147, 33));
        btnEliEliPro.setPreferredSize(new java.awt.Dimension(147, 33));
        btnEliEliPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliEliProActionPerformed(evt);
            }
        });

        btnSalEliPro.setBackground(new java.awt.Color(79, 157, 157));
        btnSalEliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalEliPro.setText("SALIR");
        btnSalEliPro.setMaximumSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.setMinimumSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.setPreferredSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalEliProActionPerformed(evt);
            }
        });

        tblEliPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpMosEliPro.setViewportView(tblEliPro);

        javax.swing.GroupLayout pnlMosEliProLayout = new javax.swing.GroupLayout(pnlMosEliPro);
        pnlMosEliPro.setLayout(pnlMosEliProLayout);
        pnlMosEliProLayout.setHorizontalGroup(
            pnlMosEliProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliProLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMosEliProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMosEliProLayout.createSequentialGroup()
                        .addComponent(btnMosEliPro)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scpMosEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlMosEliProLayout.setVerticalGroup(
            pnlMosEliProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMosEliProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMosEliProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMosEliPro))
                .addGap(11, 11, 11)
                .addComponent(scpMosEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIconoEliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoEliPro)
                        .addGap(216, 216, 216)
                        .addComponent(lblTitEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMosEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIconoEliPro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTitEliPro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMosEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMosEliProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosEliProActionPerformed
        // TODO add your handling code here:
        String Informacion = lblIconoEliPro.getText();
        CargarTabla(Informacion);
    }//GEN-LAST:event_btnMosEliProActionPerformed

    private void btnEliEliProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliEliProActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        int fila= tblEliPro.getSelectedRow();
        if(fila<0)
            {
             JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
            }
        else
        {
            int Pregunta;
            Pregunta = JOptionPane.showConfirmDialog(null,"Desea Eliminar Los Datos","Pregunta" ,0);
            if (Pregunta==0)
            {
                idfila= tblEliPro.getValueAt(fila, 0).toString();
                String eli="DELETE FROM vehiculo WHERE matri_vehi = '"+idfila+"'";
                PreparedStatement pst;
                try
                {
                    pst = cn.prepareStatement(eli);
                    int m=pst.executeUpdate();
                    if(m>0)
                    {
                        JOptionPane.showMessageDialog(this, "ELIMINO LOS DATOS DE FORMA CORRECTA");
                        String Informacion = lblIconoEliPro.getText();
                        CargarTabla(Informacion);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                        String Informacion = lblIconoEliPro.getText();
                        CargarTabla(Informacion);
                    }
                
                } catch (SQLException ex) 
                {
                    Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
      
    }//GEN-LAST:event_btnEliEliProActionPerformed

    private void btnSalEliProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalEliProActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario MenuUsuarioJF = new MenuUsuario();
        //MenuUsuarioJF.setVisible(true);
    }//GEN-LAST:event_btnSalEliProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliEliPro;
    private javax.swing.JButton btnMosEliPro;
    private javax.swing.JButton btnSalEliPro;
    private javax.swing.JLabel lblIconoEliPro;
    private javax.swing.JLabel lblTitEliPro;
    private javax.swing.JPanel pnlMosEliPro;
    private javax.swing.JScrollPane scpMosEliPro;
    private javax.swing.JTable tblEliPro;
    // End of variables declaration//GEN-END:variables

    String idfila="";
}
