package formularios;


import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
        this.getContentPane().setBackground(new Color(0,81,81));
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuConMenuUsu = new javax.swing.JLabel();
        lblUsuUsuConectado = new javax.swing.JLabel();
        mnuUsu = new javax.swing.JMenuBar();
        mnuIncUsu = new javax.swing.JMenu();
        mnuCerMenuUsu = new javax.swing.JMenuItem();
        mnuSalirUsu = new javax.swing.JMenuItem();
        mnuAdmUsu = new javax.swing.JMenu();
        mnuIngUsuAse = new javax.swing.JMenuItem();
        mnuModUsuAse = new javax.swing.JMenuItem();
        mnuIngProAse = new javax.swing.JMenuItem();
        mnuModProUsuAse = new javax.swing.JMenuItem();
        mnuEliUsuAse = new javax.swing.JMenuItem();
        mnuUsuCliPro = new javax.swing.JMenu();
        mnuUsuDatCli = new javax.swing.JMenu();
        mnuIngUsuCli = new javax.swing.JMenuItem();
        mnuModUsuCli = new javax.swing.JMenuItem();
        mnuEliUsuCli = new javax.swing.JMenuItem();
        mnuUsuDatPro = new javax.swing.JMenu();
        mnuIngUsuProd = new javax.swing.JMenuItem();
        mnuModUsuPro = new javax.swing.JMenuItem();
        mnuEliUsuPro = new javax.swing.JMenuItem();
        mnuUsuPol = new javax.swing.JMenu();
        mnuDatUsuPol = new javax.swing.JMenuItem();
        mnuBusUsuPol = new javax.swing.JMenuItem();
        mnuDatUsuPolPro = new javax.swing.JMenuItem();
        mnuUsuSin = new javax.swing.JMenu();
        mnuRegUsuSol = new javax.swing.JMenuItem();
        mnuBusUsuSol = new javax.swing.JMenuItem();
        mnuUsuCon = new javax.swing.JMenu();
        mnuConPolUsu = new javax.swing.JMenuItem();
        mnuConCliUsu = new javax.swing.JMenuItem();
        mnuConSolUsu = new javax.swing.JMenuItem();
        mnuConProUsu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmMenuUsuario"); // NOI18N

        lblUsuConMenuUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuConMenuUsu.setText("Usuario Conectado:");

        lblUsuUsuConectado.setForeground(new java.awt.Color(255, 255, 255));

        mnuIncUsu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuIncUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        mnuIncUsu.setText("Inicio                ");
        mnuIncUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuCerMenuUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuCerMenuUsu.setText("Cerrar Sesión");
        mnuCerMenuUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerMenuUsuActionPerformed(evt);
            }
        });
        mnuIncUsu.add(mnuCerMenuUsu);

        mnuSalirUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuSalirUsu.setText("Salir");
        mnuSalirUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirUsuActionPerformed(evt);
            }
        });
        mnuIncUsu.add(mnuSalirUsu);

        mnuUsu.add(mnuIncUsu);

        mnuAdmUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        mnuAdmUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/protected-profile.png"))); // NOI18N
        mnuAdmUsu.setText("Gestionar Aseguradora                  ");
        mnuAdmUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuIngUsuAse.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuIngUsuAse.setText("Ingresar Aseguradora");
        mnuIngUsuAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngUsuAseActionPerformed(evt);
            }
        });
        mnuAdmUsu.add(mnuIngUsuAse);

        mnuModUsuAse.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuModUsuAse.setText("Modificar Aseguradora");
        mnuModUsuAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModUsuAseActionPerformed(evt);
            }
        });
        mnuAdmUsu.add(mnuModUsuAse);

        mnuIngProAse.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuIngProAse.setText("Ingresar Cobertura");
        mnuIngProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngProAseActionPerformed(evt);
            }
        });
        mnuAdmUsu.add(mnuIngProAse);

        mnuModProUsuAse.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuModProUsuAse.setText("Modificar Cobertura");
        mnuModProUsuAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModProUsuAseActionPerformed(evt);
            }
        });
        mnuAdmUsu.add(mnuModProUsuAse);

        mnuEliUsuAse.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuEliUsuAse.setText("Eliminar Datos");
        mnuEliUsuAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliUsuAseActionPerformed(evt);
            }
        });
        mnuAdmUsu.add(mnuEliUsuAse);

        mnuUsu.add(mnuAdmUsu);

        mnuUsuCliPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuUsuCliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        mnuUsuCliPro.setText("Gestionar Cliente - Producto                   ");
        mnuUsuCliPro.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuUsuDatCli.setText("Datos del Cliente");
        mnuUsuDatCli.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuIngUsuCli.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuIngUsuCli.setText("Ingresar Datos");
        mnuIngUsuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngUsuCliActionPerformed(evt);
            }
        });
        mnuUsuDatCli.add(mnuIngUsuCli);

        mnuModUsuCli.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuModUsuCli.setText("Modificar Datos");
        mnuModUsuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModUsuCliActionPerformed(evt);
            }
        });
        mnuUsuDatCli.add(mnuModUsuCli);

        mnuEliUsuCli.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuEliUsuCli.setText("Eliminar Datos");
        mnuEliUsuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliUsuCliActionPerformed(evt);
            }
        });
        mnuUsuDatCli.add(mnuEliUsuCli);

        mnuUsuCliPro.add(mnuUsuDatCli);

        mnuUsuDatPro.setText("Datos del Producto");
        mnuUsuDatPro.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuIngUsuProd.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuIngUsuProd.setText("Ingresar Datos");
        mnuIngUsuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngUsuProdActionPerformed(evt);
            }
        });
        mnuUsuDatPro.add(mnuIngUsuProd);

        mnuModUsuPro.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuModUsuPro.setText("Modificar Datos");
        mnuModUsuPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModUsuProActionPerformed(evt);
            }
        });
        mnuUsuDatPro.add(mnuModUsuPro);

        mnuEliUsuPro.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuEliUsuPro.setText("Eliminar Datos");
        mnuEliUsuPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliUsuProActionPerformed(evt);
            }
        });
        mnuUsuDatPro.add(mnuEliUsuPro);

        mnuUsuCliPro.add(mnuUsuDatPro);

        mnuUsu.add(mnuUsuCliPro);

        mnuUsuPol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuUsuPol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrato.png"))); // NOI18N
        mnuUsuPol.setText("Generar Poliza Seguro                      ");
        mnuUsuPol.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuDatUsuPol.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuDatUsuPol.setText("Ingresar Datos Poliza");
        mnuDatUsuPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDatUsuPolActionPerformed(evt);
            }
        });
        mnuUsuPol.add(mnuDatUsuPol);

        mnuBusUsuPol.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuBusUsuPol.setText("Buscar Póliza");
        mnuBusUsuPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusUsuPolActionPerformed(evt);
            }
        });
        mnuUsuPol.add(mnuBusUsuPol);

        mnuDatUsuPolPro.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuDatUsuPolPro.setText("Cobertura General");
        mnuDatUsuPolPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDatUsuPolProActionPerformed(evt);
            }
        });
        mnuUsuPol.add(mnuDatUsuPolPro);

        mnuUsu.add(mnuUsuPol);

        mnuUsuSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuUsuSin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/solicitud.png"))); // NOI18N
        mnuUsuSin.setText("Solicitudes del Siniestro                  ");
        mnuUsuSin.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuRegUsuSol.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuRegUsuSol.setText("Registrar Solicitud");
        mnuRegUsuSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegUsuSolActionPerformed(evt);
            }
        });
        mnuUsuSin.add(mnuRegUsuSol);

        mnuBusUsuSol.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuBusUsuSol.setText("Buscar Solicitud");
        mnuBusUsuSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusUsuSolActionPerformed(evt);
            }
        });
        mnuUsuSin.add(mnuBusUsuSol);

        mnuUsu.add(mnuUsuSin);

        mnuUsuCon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuUsuCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportar.png"))); // NOI18N
        mnuUsuCon.setText("Consultas");
        mnuUsuCon.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        mnuConPolUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuConPolUsu.setText("Consulta Póliza");
        mnuConPolUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConPolUsuActionPerformed(evt);
            }
        });
        mnuUsuCon.add(mnuConPolUsu);

        mnuConCliUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuConCliUsu.setText("Consulta Clientes");
        mnuConCliUsu.setToolTipText("");
        mnuConCliUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConCliUsuActionPerformed(evt);
            }
        });
        mnuUsuCon.add(mnuConCliUsu);

        mnuConSolUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuConSolUsu.setText("Consulta Solicitudes");
        mnuConSolUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConSolUsuActionPerformed(evt);
            }
        });
        mnuUsuCon.add(mnuConSolUsu);

        mnuConProUsu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        mnuConProUsu.setText("Consulta Productos");
        mnuConProUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConProUsuActionPerformed(evt);
            }
        });
        mnuUsuCon.add(mnuConProUsu);

        mnuUsu.add(mnuUsuCon);

        setJMenuBar(mnuUsu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuConMenuUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuUsuConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1080, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(587, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuConMenuUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuUsuConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCerMenuUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerMenuUsuActionPerformed
        // TODO add your handling code here:
        IngresoSistema principal= new IngresoSistema();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuCerMenuUsuActionPerformed

    private void mnuSalirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirUsuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirUsuActionPerformed

    private void mnuIngUsuAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngUsuAseActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        RegAseguradora InforAseguradorasJF = new RegAseguradora();
        InforAseguradorasJF.setVisible(true);
    }//GEN-LAST:event_mnuIngUsuAseActionPerformed

    private void mnuModUsuAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModUsuAseActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        ModAseguradora ModAseguradorasJF = new ModAseguradora();
        ModAseguradorasJF.setVisible(true);
    }//GEN-LAST:event_mnuModUsuAseActionPerformed

    private void mnuEliUsuAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliUsuAseActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        EliAseguradora EliAseguradorasJF = new EliAseguradora();
        EliAseguradorasJF.setVisible(true);
    }//GEN-LAST:event_mnuEliUsuAseActionPerformed

    private void mnuIngUsuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngUsuCliActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        RegCliente InfClienteJF = new RegCliente();
        InfClienteJF.setVisible(true);
    }//GEN-LAST:event_mnuIngUsuCliActionPerformed

    private void mnuModUsuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModUsuCliActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        ModCliente ModClienteJF = new ModCliente();
        ModClienteJF.setVisible(true);
    }//GEN-LAST:event_mnuModUsuCliActionPerformed

    private void mnuEliUsuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliUsuCliActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        EliCliente EliClienteJF = new EliCliente();
        EliClienteJF.setVisible(true);
    }//GEN-LAST:event_mnuEliUsuCliActionPerformed

    private void mnuIngUsuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngUsuProdActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        RegProducto InfProductoJF = new RegProducto();
        InfProductoJF.setVisible(true);
    }//GEN-LAST:event_mnuIngUsuProdActionPerformed

    private void mnuModUsuProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModUsuProActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        ModProducto ModProductoJF = new ModProducto();
        ModProductoJF.setVisible(true);
    }//GEN-LAST:event_mnuModUsuProActionPerformed

    private void mnuEliUsuProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliUsuProActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        EliProducto EliProductoJF = new EliProducto();
        EliProductoJF.setVisible(true);
    }//GEN-LAST:event_mnuEliUsuProActionPerformed

    private void mnuDatUsuPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDatUsuPolActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        RegPoliza InfPolizaJF = new RegPoliza();
        InfPolizaJF.setVisible(true);
    }//GEN-LAST:event_mnuDatUsuPolActionPerformed

    private void mnuRegUsuSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegUsuSolActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        RegSolicitud RegSolicitudJF = new RegSolicitud();
        RegSolicitudJF.setVisible(true);
    }//GEN-LAST:event_mnuRegUsuSolActionPerformed

    private void mnuBusUsuSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusUsuSolActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        BusSolicitud BusSolicitudJF = new BusSolicitud();
        BusSolicitudJF.setVisible(true);
    }//GEN-LAST:event_mnuBusUsuSolActionPerformed

    private void mnuIngProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngProAseActionPerformed
        // TODO add your handling code here:
        ProAseguradora IngProformaJF = new ProAseguradora();
        IngProformaJF.setVisible(true);
    }//GEN-LAST:event_mnuIngProAseActionPerformed

    private void mnuBusUsuPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusUsuPolActionPerformed
        // TODO add your handling code here:
        BusPoliza BusPolizaJF = new BusPoliza();
        BusPolizaJF.setVisible(true);
    }//GEN-LAST:event_mnuBusUsuPolActionPerformed

    private void mnuDatUsuPolProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDatUsuPolProActionPerformed
        // TODO add your handling code here:
        MosInfProformas InfProformasJF = new MosInfProformas();
        InfProformasJF.setVisible(true);
    }//GEN-LAST:event_mnuDatUsuPolProActionPerformed

    private void mnuConPolUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConPolUsuActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        ConPoliza ConPolizaJF = new ConPoliza();
        ConPolizaJF.setVisible(true);
    }//GEN-LAST:event_mnuConPolUsuActionPerformed

    private void mnuConCliUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConCliUsuActionPerformed
        // TODO add your handling code here:
        ConCliente ConClienteJF = new ConCliente();
        ConClienteJF.setVisible(true);
    }//GEN-LAST:event_mnuConCliUsuActionPerformed

    private void mnuConSolUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConSolUsuActionPerformed
        // TODO add your handling code here:
        ConSolicitud ConSolicitudJF = new ConSolicitud();
        ConSolicitudJF.setVisible(true);
    }//GEN-LAST:event_mnuConSolUsuActionPerformed

    private void mnuConProUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConProUsuActionPerformed
        // TODO add your handling code here:
        ConProducto ConProductoJF = new ConProducto();
        ConProductoJF.setVisible(true);
    }//GEN-LAST:event_mnuConProUsuActionPerformed

    private void mnuModProUsuAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModProUsuAseActionPerformed
        // TODO add your handling code here:
        ModProAseguradora ModProAseguradoraJF = new ModProAseguradora();
        ModProAseguradoraJF.setVisible(true);
    }//GEN-LAST:event_mnuModProUsuAseActionPerformed

    /**
   mnuUsuConm args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblUsuConMenuUsu;
    public static javax.swing.JLabel lblUsuUsuConectado;
    private javax.swing.JMenu mnuAdmUsu;
    private javax.swing.JMenuItem mnuBusUsuPol;
    private javax.swing.JMenuItem mnuBusUsuSol;
    private javax.swing.JMenuItem mnuCerMenuUsu;
    private javax.swing.JMenuItem mnuConCliUsu;
    private javax.swing.JMenuItem mnuConPolUsu;
    private javax.swing.JMenuItem mnuConProUsu;
    private javax.swing.JMenuItem mnuConSolUsu;
    private javax.swing.JMenuItem mnuDatUsuPol;
    private javax.swing.JMenuItem mnuDatUsuPolPro;
    private javax.swing.JMenuItem mnuEliUsuAse;
    private javax.swing.JMenuItem mnuEliUsuCli;
    private javax.swing.JMenuItem mnuEliUsuPro;
    private javax.swing.JMenu mnuIncUsu;
    private javax.swing.JMenuItem mnuIngProAse;
    private javax.swing.JMenuItem mnuIngUsuAse;
    private javax.swing.JMenuItem mnuIngUsuCli;
    private javax.swing.JMenuItem mnuIngUsuProd;
    private javax.swing.JMenuItem mnuModProUsuAse;
    private javax.swing.JMenuItem mnuModUsuAse;
    private javax.swing.JMenuItem mnuModUsuCli;
    private javax.swing.JMenuItem mnuModUsuPro;
    private javax.swing.JMenuItem mnuRegUsuSol;
    private javax.swing.JMenuItem mnuSalirUsu;
    private javax.swing.JMenuBar mnuUsu;
    private javax.swing.JMenu mnuUsuCliPro;
    private javax.swing.JMenu mnuUsuCon;
    private javax.swing.JMenu mnuUsuDatCli;
    private javax.swing.JMenu mnuUsuDatPro;
    private javax.swing.JMenu mnuUsuPol;
    private javax.swing.JMenu mnuUsuSin;
    // End of variables declaration//GEN-END:variables
}
