package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class MosInfProformas extends javax.swing.JFrame {
DefaultTableModel Proformas;
    /**
     * Creates new form MosInfProformas
     */
    public MosInfProformas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        Cargar_Pro();
    }
    
    void Cargar_Pro()
    {
        try
        {
            String[] Titulos = {"CÓDIGO","EMPRESA","CÓDIGO EMPRESA","POR ROBO","COBERTURA %","POR ACCIDENTE","COBERTURA %","POR HOSPITAL","COBERTURA %","ANTIGUEDAD DEL VEHÍCULO","RESPONSABILIDAD CIVIL"};
            String[] Informacion = new String[11];

            String sSQL="";

            Proformas = new DefaultTableModel(null, Titulos);

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL= "SELECT cod_pro, nom_emp, cod_emp, robo, por_robo, accidente, por_acci, medico, por_med , ant_veh, res_civ FROM proforma";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Informacion[0]= rs.getString("cod_pro");
                Informacion[1]= rs.getString("nom_emp");
                Informacion[2] = rs.getString("cod_emp");
                Informacion[3] = rs.getString("robo");
                Informacion[4] = rs.getString("por_robo");
                Informacion[5] = rs.getString("accidente");
                Informacion[6] = rs.getString("por_acci");
                Informacion[7] = rs.getString("medico");
                Informacion[8] = rs.getString("por_med");
                Informacion[9] = rs.getString("ant_veh");
                Informacion[10] = rs.getString("res_civ");

                Proformas.addRow(Informacion);
            }
            tblMosInfPro.setModel(Proformas);
        }   
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitMosInfPro = new javax.swing.JLabel();
        lblIconoMosInfPro = new javax.swing.JLabel();
        scpMosInfPro = new javax.swing.JScrollPane();
        tblMosInfPro = new javax.swing.JTable();
        btnSalirMosInfPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");

        lblTitMosInfPro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitMosInfPro.setText("LISTADO DE COBERTURAS GENERALES DE LAS ASEGURADORAS");

        lblIconoMosInfPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoMosProforma.jpg"))); // NOI18N

        tblMosInfPro.setBackground(new java.awt.Color(153, 255, 255));
        tblMosInfPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpMosInfPro.setViewportView(tblMosInfPro);

        btnSalirMosInfPro.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirMosInfPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirMosInfPro.setText("SALIR");
        btnSalirMosInfPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMosInfProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoMosInfPro)
                        .addGap(110, 110, 110)
                        .addComponent(lblTitMosInfPro)
                        .addGap(0, 314, Short.MAX_VALUE))
                    .addComponent(scpMosInfPro))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(btnSalirMosInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoMosInfPro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitMosInfPro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMosInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSalirMosInfPro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMosInfProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMosInfProActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirMosInfProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MosInfProformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MosInfProformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MosInfProformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MosInfProformas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MosInfProformas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirMosInfPro;
    private javax.swing.JLabel lblIconoMosInfPro;
    private javax.swing.JLabel lblTitMosInfPro;
    private javax.swing.JScrollPane scpMosInfPro;
    private javax.swing.JTable tblMosInfPro;
    // End of variables declaration//GEN-END:variables
}
