package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class ProAseguradora extends javax.swing.JFrame {
DefaultComboBoxModel proforma;
    /**
     * Creates new form Proforma
     */
    public ProAseguradora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        cargar();
        cboNomProAse.setEditable(true); //para poder escribir adentro
        AutoCompleteDecorator.decorate(this.cboNomProAse);
        txtCodProAse.setVisible(false);
        
    }
    
    void cargar()
    {
        try
        {
            String Nombre;

            String sSQL="";

            proforma = new DefaultComboBoxModel();

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
   
            sSQL = "SELECT nom_emp FROM aseguradora";

            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Nombre = rs.getString("nom_emp");
                proforma.addElement(Nombre);
            }
            cboNomProAse.setModel(proforma);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }
    }



    void CargarCodigo(String Codigo)
    {
        try
        {
            String sSQL = "";
            String Guardar = "";

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT cod_emp FROM aseguradora " + "WHERE CONCAT(nom_emp) LIKE '%"+Codigo+"%'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Guardar = rs.getString("cod_emp");

            }
            txtCodProAse.setText(Guardar);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void borrar()
    {
        txtCodProProAse.setText("");
        txtPorRoboProAse.setText("");
        txtPorAccAse.setText("");
        txtPorMedProAse.setText("");
        cboRoboProAse.setSelectedItem("Seleccione");
        cboAccProAse.setSelectedItem("Seleccione");
        cboMedProAse.setSelectedItem("Seleccione");
        cboAntProAse.setSelectedItem("Seleccione");
        cboResProAse.setSelectedItem("Seleccione");
       
    }
        
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirProAse = new javax.swing.JButton();
        btnCancelarProAse = new javax.swing.JButton();
        btnGuardarProAse = new javax.swing.JButton();
        pnlDatProAse = new javax.swing.JPanel();
        lblTipProAse = new javax.swing.JLabel();
        cboAntProAse = new javax.swing.JComboBox();
        lblRoboProAse = new javax.swing.JLabel();
        lblAccProAse = new javax.swing.JLabel();
        lblMedProAse = new javax.swing.JLabel();
        cboRoboProAse = new javax.swing.JComboBox();
        cboAccProAse = new javax.swing.JComboBox();
        cboMedProAse = new javax.swing.JComboBox();
        lblPorMedProAse = new javax.swing.JLabel();
        txtPorMedProAse = new javax.swing.JTextField();
        lblPorAccAse = new javax.swing.JLabel();
        txtPorAccAse = new javax.swing.JTextField();
        lblPorRoboProAse = new javax.swing.JLabel();
        txtPorRoboProAse = new javax.swing.JTextField();
        lblCodProAse = new javax.swing.JLabel();
        txtCodProProAse = new javax.swing.JTextField();
        lblTipProAse1 = new javax.swing.JLabel();
        cboResProAse = new javax.swing.JComboBox();
        lblTitProAse = new javax.swing.JLabel();
        pnlNomProAse = new javax.swing.JPanel();
        cboNomProAse = new javax.swing.JComboBox();
        txtCodProAse = new javax.swing.JTextField();
        lblIconoProAse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmProforma"); // NOI18N

        btnSalirProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirProAse.setText("SALIR");
        btnSalirProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnSalirProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnSalirProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnSalirProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProAseActionPerformed(evt);
            }
        });

        btnCancelarProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnCancelarProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelarProAse.setText("CANCELAR");
        btnCancelarProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnCancelarProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnCancelarProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnCancelarProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProAseActionPerformed(evt);
            }
        });

        btnGuardarProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnGuardarProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardarProAse.setText("GUARDAR");
        btnGuardarProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnGuardarProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnGuardarProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnGuardarProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProAseActionPerformed(evt);
            }
        });

        pnlDatProAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlDatProAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Que Ofrece Aseguradora"));

        lblTipProAse.setText("Antiguedad del Vehículo *");

        cboAntProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Hasta 10 años de fabricación", "Hasta 12 años de fabricación", "Hasta 13 años de fabricación", "Hasta 14 años de fabricación", "Hasta 15 años de fabricación" }));

        lblRoboProAse.setText("Pérdida Por Robo *");

        lblAccProAse.setText("Pérdida Por Accidente *");

        lblMedProAse.setText("Gatos Médicos *");

        cboRoboProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        cboAccProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        cboMedProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        lblPorMedProAse.setText("Porcentaje de Cobertura *       %");

        lblPorAccAse.setText("Porcentaje de Cobertura *       %");

        lblPorRoboProAse.setText("Porcentaje de Cobertura *       %");

        lblCodProAse.setText("Código Cobertura *");

        txtCodProProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProProAseActionPerformed(evt);
            }
        });

        lblTipProAse1.setText("Responsabilidad Civil *");

        cboResProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "En Ecuador", "No aplica fuera del Ecuador", "Dentro de territorio ecuatoriano", "Aplica dentro de Comunidad Andina" }));

        javax.swing.GroupLayout pnlDatProAseLayout = new javax.swing.GroupLayout(pnlDatProAse);
        pnlDatProAse.setLayout(pnlDatProAseLayout);
        pnlDatProAseLayout.setHorizontalGroup(
            pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccProAse)
                    .addComponent(lblRoboProAse)
                    .addComponent(lblTipProAse)
                    .addComponent(lblMedProAse)
                    .addComponent(lblCodProAse)
                    .addComponent(lblTipProAse1))
                .addGap(33, 33, 33)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboResProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAccProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMedProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAntProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboRoboProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodProProAse))
                .addGap(47, 47, 47)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPorAccAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPorRoboProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPorMedProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorMedProAse, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtPorRoboProAse)
                    .addComponent(txtPorAccAse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatProAseLayout.setVerticalGroup(
            pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatProAseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProAse)
                    .addComponent(txtCodProProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPorMedProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRoboProAse)
                        .addComponent(cboRoboProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPorRoboProAse)))
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatProAseLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccProAse)
                            .addComponent(cboAccProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPorAccAse)))
                    .addGroup(pnlDatProAseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPorRoboProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMedProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedProAse)
                    .addComponent(lblPorMedProAse)
                    .addComponent(txtPorAccAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAntProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipProAse))
                .addGap(20, 20, 20)
                .addGroup(pnlDatProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboResProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipProAse1))
                .addGap(15, 15, 15))
        );

        lblTitProAse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitProAse.setText("COBERTURA GENERAL DE LA ASEGURADORA");

        pnlNomProAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlNomProAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre De La Empresa"));

        cboNomProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomProAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNomProAseLayout = new javax.swing.GroupLayout(pnlNomProAse);
        pnlNomProAse.setLayout(pnlNomProAseLayout);
        pnlNomProAseLayout.setHorizontalGroup(
            pnlNomProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNomProAse, 0, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNomProAseLayout.setVerticalGroup(
            pnlNomProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNomProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCodProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProAseActionPerformed(evt);
            }
        });

        lblIconoProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoProforma.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIconoProAse)
                                .addGap(33, 33, 33)
                                .addComponent(lblTitProAse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlNomProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(txtCodProAse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDatProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnGuardarProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCancelarProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalirProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoProAse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTitProAse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCodProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addComponent(pnlNomProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnlDatProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalirProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProAseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RegAseguradora InfAseguradoraJF = new RegAseguradora();
        InfAseguradoraJF.setVisible(true);
    }//GEN-LAST:event_btnSalirProAseActionPerformed

    private void btnCancelarProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProAseActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_btnCancelarProAseActionPerformed

    private void btnGuardarProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProAseActionPerformed
        // TODO add your handling code here:
        try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            String sSQL=("");
            String Mensaje=("");

            String Nombre_Emp;
            String Robo;
            String Acci;
            String Medi;
            String Cod_Pro;
            String Por_Robo;
            String Por_Acci;
            String Por_Medi;
            String Ant_v;
            String Res_v;
            String Cod_Emp;

            Nombre_Emp = cboNomProAse.getSelectedItem().toString();
            Robo = cboRoboProAse.getSelectedItem().toString();
            Acci = cboAccProAse.getSelectedItem().toString();
            Medi = cboMedProAse.getSelectedItem().toString();
            Cod_Pro = txtCodProProAse.getText();
            Por_Robo = txtPorRoboProAse.getText();
            Por_Acci = txtPorAccAse.getText();
            Por_Medi = txtPorMedProAse.getText();
            Ant_v = cboAntProAse.getSelectedItem().toString();
            Res_v = cboResProAse.getSelectedItem().toString();
            Cod_Emp = txtCodProAse.getText();

            if(Robo.equals("Seleccione")||Acci.equals("Seleccione")||
                Medi.equals("Seleccione")||Cod_Pro.equals("")||Por_Robo.equals("")||Por_Acci.equals("")||
                Por_Medi.equals("")||Ant_v.equals("Seleccione")||Res_v.equals("Seleccione")||Cod_Emp.equals("")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }

            else{
                if(ValidarNum(Cod_Pro)==false||ValidarNum(Por_Robo)==false||ValidarNum(Por_Acci)==false||ValidarNum(Por_Medi)==false){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }

                else{
                    sSQL = "INSERT INTO proforma(nom_emp, robo, accidente, medico, cod_pro, por_robo, por_acci, por_med, ant_veh, res_civ, cod_emp)" +
                    "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                    Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                    PreparedStatement pst = cn.prepareStatement(sSQL);

                    pst.setString(1, Nombre_Emp);
                    pst.setString(2, Robo);
                    pst.setString(3, Acci);
                    pst.setString(4, Medi);
                    pst.setString(5, Cod_Pro);
                    pst.setString(6, Por_Robo);
                    pst.setString(7, Por_Acci);
                    pst.setString(8, Por_Medi);
                    pst.setString(9, Ant_v);
                    pst.setString(10, Res_v);
                    pst.setString(11, Cod_Emp);

                    int n = pst.executeUpdate();

                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null, Mensaje);
                    }
                    borrar();
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnGuardarProAseActionPerformed

    private void cboNomProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomProAseActionPerformed
        // TODO add your handling code here:
        String Codigo = cboNomProAse.getSelectedItem().toString();
        CargarCodigo(Codigo);
    }//GEN-LAST:event_cboNomProAseActionPerformed

    private void txtCodProProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProProAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProProAseActionPerformed

    private void txtCodProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProAseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProAseguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProAse;
    private javax.swing.JButton btnGuardarProAse;
    private javax.swing.JButton btnSalirProAse;
    private javax.swing.JComboBox cboAccProAse;
    private javax.swing.JComboBox cboAntProAse;
    private javax.swing.JComboBox cboMedProAse;
    private javax.swing.JComboBox cboNomProAse;
    private javax.swing.JComboBox cboResProAse;
    private javax.swing.JComboBox cboRoboProAse;
    private javax.swing.JLabel lblAccProAse;
    private javax.swing.JLabel lblCodProAse;
    private javax.swing.JLabel lblIconoProAse;
    private javax.swing.JLabel lblMedProAse;
    private javax.swing.JLabel lblPorAccAse;
    private javax.swing.JLabel lblPorMedProAse;
    private javax.swing.JLabel lblPorRoboProAse;
    private javax.swing.JLabel lblRoboProAse;
    private javax.swing.JLabel lblTipProAse;
    private javax.swing.JLabel lblTipProAse1;
    private javax.swing.JLabel lblTitProAse;
    private javax.swing.JPanel pnlDatProAse;
    private javax.swing.JPanel pnlNomProAse;
    private javax.swing.JTextField txtCodProAse;
    private javax.swing.JTextField txtCodProProAse;
    private javax.swing.JTextField txtPorAccAse;
    private javax.swing.JTextField txtPorMedProAse;
    private javax.swing.JTextField txtPorRoboProAse;
    // End of variables declaration//GEN-END:variables
}
