package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class RegAseguradora extends javax.swing.JFrame {

    /**
     * Creates new form InforAseguradoras
     */
    public RegAseguradora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    void borrar()
    {
            txtCodRegAse.setText("");
            txtNomRegAse.setText("");
            txtCiuRegAse.setText("");
            txtDirRegAse.setText("");
            txtGerRegAse.setText("");
            txtTelfRegAse.setText("");
            txtMailRegAse.setText("");
    }
    
    boolean ValidarLetras(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 31 && palabra.charAt(i) < 91) || (palabra.charAt(i) > 96 && palabra.charAt(i) < 123)))
                return false;
        }
        return true;
    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoRegAse = new javax.swing.JLabel();
        lblTituloRegAse = new javax.swing.JLabel();
        pnlDatosRegAse = new javax.swing.JPanel();
        lblNomRegAse = new javax.swing.JLabel();
        lblCiuRegAse = new javax.swing.JLabel();
        lblDirRegAse = new javax.swing.JLabel();
        lblGerRegAse = new javax.swing.JLabel();
        lblTelfRegAse = new javax.swing.JLabel();
        lblMailRegAse = new javax.swing.JLabel();
        txtNomRegAse = new javax.swing.JTextField();
        txtCiuRegAse = new javax.swing.JTextField();
        txtDirRegAse = new javax.swing.JTextField();
        txtGerRegAse = new javax.swing.JTextField();
        txtTelfRegAse = new javax.swing.JTextField();
        txtMailRegAse = new javax.swing.JTextField();
        lblCodRegAse = new javax.swing.JLabel();
        txtCodRegAse = new javax.swing.JTextField();
        btnIngProEmp = new javax.swing.JButton();
        btnCancelarRegAse = new javax.swing.JButton();
        btnSalirRegAse = new javax.swing.JButton();
        btnGuardarRegAse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmRegAseguradora"); // NOI18N

        lblIconoRegAse.setBackground(new java.awt.Color(69, 139, 116));
        lblIconoRegAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empresa.png"))); // NOI18N

        lblTituloRegAse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloRegAse.setText("DATOS DE LA ASEGURADORA ");

        pnlDatosRegAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlDatosRegAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato Empresa Aseguradora"));

        lblNomRegAse.setText("Nombre Empresa *");

        lblCiuRegAse.setText("Ciudad *");

        lblDirRegAse.setText("Dirección *");

        lblGerRegAse.setText("Gerente *");

        lblTelfRegAse.setText("Teléfono *");

        lblMailRegAse.setText("E-Mail *");

        txtNomRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomRegAseActionPerformed(evt);
            }
        });
        txtNomRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomRegAseKeyTyped(evt);
            }
        });

        txtCiuRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiuRegAseKeyTyped(evt);
            }
        });

        txtDirRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirRegAseKeyTyped(evt);
            }
        });

        txtGerRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGerRegAseKeyTyped(evt);
            }
        });

        txtTelfRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelfRegAseKeyTyped(evt);
            }
        });

        txtMailRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailRegAseActionPerformed(evt);
            }
        });
        txtMailRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailRegAseKeyTyped(evt);
            }
        });

        lblCodRegAse.setText("Código Empresa *");

        txtCodRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRegAseActionPerformed(evt);
            }
        });
        txtCodRegAse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodRegAseKeyTyped(evt);
            }
        });

        btnIngProEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnIngProEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngProEmp.setText("INGRESO DE INFORMACIÓN GENERAL DE COBERTURA DE LA EMPRESA");
        btnIngProEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngProEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosRegAseLayout = new javax.swing.GroupLayout(pnlDatosRegAse);
        pnlDatosRegAse.setLayout(pnlDatosRegAseLayout);
        pnlDatosRegAseLayout.setHorizontalGroup(
            pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDirRegAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCiuRegAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodRegAse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomRegAse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                        .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNomRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosRegAseLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCodRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosRegAseLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCiuRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMailRegAse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosRegAseLayout.createSequentialGroup()
                                    .addComponent(lblGerRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGerRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosRegAseLayout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(txtMailRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                                    .addComponent(lblTelfRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelfRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosRegAseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngProEmp)
                            .addComponent(txtDirRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127))))
        );
        pnlDatosRegAseLayout.setVerticalGroup(
            pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCodRegAse))
                    .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGerRegAse)
                        .addComponent(txtGerRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNomRegAse))
                    .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelfRegAse)
                        .addComponent(txtTelfRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCiuRegAse))
                    .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCiuRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMailRegAse)
                        .addComponent(txtMailRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosRegAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosRegAseLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDirRegAse))
                    .addComponent(txtDirRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngProEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelarRegAse.setBackground(new java.awt.Color(79, 157, 157));
        btnCancelarRegAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelarRegAse.setText("CANCELAR");
        btnCancelarRegAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnCancelarRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegAseActionPerformed(evt);
            }
        });

        btnSalirRegAse.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirRegAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirRegAse.setText("SALIR");
        btnSalirRegAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnSalirRegAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnSalirRegAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnSalirRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegAseActionPerformed(evt);
            }
        });

        btnGuardarRegAse.setBackground(new java.awt.Color(79, 157, 157));
        btnGuardarRegAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardarRegAse.setText("GUARDAR");
        btnGuardarRegAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnGuardarRegAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(lblTituloRegAse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCancelarRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSalirRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblTituloRegAse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnSalirRegAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarRegAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomRegAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomRegAseActionPerformed

    private void txtMailRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailRegAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailRegAseActionPerformed

    private void btnCancelarRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegAseActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_btnCancelarRegAseActionPerformed

    private void btnSalirRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegAseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario MenuUsuarioJF = new MenuUsuario ();
        //MenuUsuarioJF.setVisible(true);
    }//GEN-LAST:event_btnSalirRegAseActionPerformed
   // String accion="Insertar";
    private void btnGuardarRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegAseActionPerformed
        // TODO add your handling code here:
        try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            String sSQL="";
            String Mensaje="";

            String Cod_Emp;
            String Nom_Em;
            String Ciu;
            String Dir;
            String Ger;
            String Telf;
            String Mail;


            Cod_Emp = txtCodRegAse.getText();
            Nom_Em = txtNomRegAse.getText();
            Ciu = txtCiuRegAse.getText();
            Dir = txtDirRegAse.getText();
            Ger = txtGerRegAse.getText();
            Telf = txtTelfRegAse.getText();
            Mail = txtMailRegAse.getText();
            
            if(Nom_Em.equals("")||Ciu.equals("")||Dir.equals("")||Ger.equals("")||Telf.equals("")||Mail.equals("")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }
            
            else{
                if(ValidarNum(Cod_Emp)==false||ValidarLetras(Ciu)==false||ValidarNum(Telf)==false){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }
                
                else{
                    try
                    {
                
                    sSQL = "INSERT INTO aseguradora(cod_emp, nom_emp, ciu, dir, ger, telf, mail)"
                            + "VALUES(?, ?, ?, ?, ?, ?, ?)";

                    Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                    PreparedStatement pst = cn.prepareStatement(sSQL);

                    pst.setString(1, Cod_Emp);
                    pst.setString(2, Nom_Em);
                    pst.setString(3, Ciu);
                    pst.setString(4, Dir);
                    pst.setString(5, Ger);
                    pst.setString(6, Telf);
                    pst.setString(7, Mail);

                    int n = pst.executeUpdate();

                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null, Mensaje);
                    }
                    }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) 
                        {
                            JOptionPane.showMessageDialog(null, "La Aseguradora ya esta registrado");
                        }
                    borrar();
                    
                }
              }
            }
        
            catch (Exception e)
            {
                    JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnGuardarRegAseActionPerformed

    private void txtCodRegAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRegAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRegAseActionPerformed

    private void btnIngProEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngProEmpActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ProAseguradora ProAseguradoraJF = new ProAseguradora();
        ProAseguradoraJF.setVisible(true);
    }//GEN-LAST:event_btnIngProEmpActionPerformed

    private void txtCodRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodRegAseKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodRegAseKeyTyped

    private void txtGerRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGerRegAseKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
            if(Character.isLowerCase(c))
            {
                String cad = (""+c).toUpperCase();
                c=cad.charAt(0);
                evt.setKeyChar(c);
                
            }
    }//GEN-LAST:event_txtGerRegAseKeyTyped

    private void txtNomRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomRegAseKeyTyped
        // TODO add your handling code here:
       
         char c = evt.getKeyChar();
            if(Character.isLowerCase(c))
            {
                String cad = (""+c).toUpperCase();
                c=cad.charAt(0);
                evt.setKeyChar(c);
                
            }
    }//GEN-LAST:event_txtNomRegAseKeyTyped

    private void txtTelfRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelfRegAseKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtTelfRegAseKeyTyped

    private void txtCiuRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiuRegAseKeyTyped
        // TODO add your handling code here:
        String texto = txtCiuRegAse.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtCiuRegAse.setText(texto);
        }          
    }//GEN-LAST:event_txtCiuRegAseKeyTyped

    private void txtMailRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailRegAseKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
            if(Character.isUpperCase(c))
            {
                String cad = (""+c).toLowerCase();
                c=cad.charAt(0);
                evt.setKeyChar(c);
                
            }
    }//GEN-LAST:event_txtMailRegAseKeyTyped

    private void txtDirRegAseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirRegAseKeyTyped
        // TODO add your handling code here:
        String texto = txtDirRegAse.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtDirRegAse.setText(texto);
        }     
    }//GEN-LAST:event_txtDirRegAseKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegAseguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegAse;
    private javax.swing.JButton btnGuardarRegAse;
    private javax.swing.JButton btnIngProEmp;
    private javax.swing.JButton btnSalirRegAse;
    private javax.swing.JLabel lblCiuRegAse;
    private javax.swing.JLabel lblCodRegAse;
    private javax.swing.JLabel lblDirRegAse;
    private javax.swing.JLabel lblGerRegAse;
    private javax.swing.JLabel lblIconoRegAse;
    private javax.swing.JLabel lblMailRegAse;
    private javax.swing.JLabel lblNomRegAse;
    private javax.swing.JLabel lblTelfRegAse;
    private javax.swing.JLabel lblTituloRegAse;
    private javax.swing.JPanel pnlDatosRegAse;
    private javax.swing.JTextField txtCiuRegAse;
    private javax.swing.JTextField txtCodRegAse;
    private javax.swing.JTextField txtDirRegAse;
    private javax.swing.JTextField txtGerRegAse;
    private javax.swing.JTextField txtMailRegAse;
    private javax.swing.JTextField txtNomRegAse;
    private javax.swing.JTextField txtTelfRegAse;
    // End of variables declaration//GEN-END:variables
}
