package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class RegCliente extends javax.swing.JFrame {

    /**
     * Creates new form InfCliente
     */
    public RegCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
    }
    
    void Borrar()
    {
        txtPriNomCliente.setText("");
        txtSegNomCliente.setText("");
        txtPriApeCliente.setText("");
        txtSegApeCliente.setText("");
        txtCedCliente.setText("");
        dtpFecNacCliente.setDate(null);
        txtCiuCliente.setText("");
        txtDirCliente.setText("");
        txtTelCliente.setText("");
        txtMailCliente.setText("");
    }
    
    boolean ValidarLetras(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 64 && palabra.charAt(i) < 91) || (palabra.charAt(i) > 96 && palabra.charAt(i) < 123)))
                return false;
        }
        return true;
    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoRegCli = new javax.swing.JLabel();
        lblTitRegCli = new javax.swing.JLabel();
        btnCancelarRegCli = new javax.swing.JButton();
        btnSalirRegCli = new javax.swing.JButton();
        btnGuardarRegCli = new javax.swing.JButton();
        pnlInfCliente = new javax.swing.JPanel();
        lblPriNomCliente = new javax.swing.JLabel();
        lblCedCliente = new javax.swing.JLabel();
        lblCiuCliente = new javax.swing.JLabel();
        lblDirCliente = new javax.swing.JLabel();
        lblTelCliente = new javax.swing.JLabel();
        lblMailCliente = new javax.swing.JLabel();
        lblGenCliente = new javax.swing.JLabel();
        txtPriNomCliente = new javax.swing.JTextField();
        txtCedCliente = new javax.swing.JTextField();
        txtCiuCliente = new javax.swing.JTextField();
        txtDirCliente = new javax.swing.JTextField();
        txtTelCliente = new javax.swing.JTextField();
        txtMailCliente = new javax.swing.JTextField();
        cboGenCliente = new javax.swing.JComboBox<>();
        dtpFecNacCliente = new com.toedter.calendar.JDateChooser();
        lblFecNacCliente = new javax.swing.JLabel();
        lblPriApeCliente = new javax.swing.JLabel();
        lblSegNomCliente = new javax.swing.JLabel();
        lblSegApeCliente = new javax.swing.JLabel();
        txtSegNomCliente = new javax.swing.JTextField();
        txtPriApeCliente = new javax.swing.JTextField();
        txtSegApeCliente = new javax.swing.JTextField();
        lblSegNomModCli1 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmRegCliente"); // NOI18N

        lblIconoRegCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N

        lblTitRegCli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitRegCli.setText("DATOS DEL CLIENTE ");

        btnCancelarRegCli.setBackground(new java.awt.Color(79, 157, 157));
        btnCancelarRegCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelarRegCli.setText("CANCELAR");
        btnCancelarRegCli.setMaximumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegCli.setMinimumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegCli.setPreferredSize(new java.awt.Dimension(122, 33));
        btnCancelarRegCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegCliActionPerformed(evt);
            }
        });

        btnSalirRegCli.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirRegCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirRegCli.setText("SALIR");
        btnSalirRegCli.setMaximumSize(new java.awt.Dimension(122, 33));
        btnSalirRegCli.setMinimumSize(new java.awt.Dimension(122, 33));
        btnSalirRegCli.setPreferredSize(new java.awt.Dimension(122, 33));
        btnSalirRegCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegCliActionPerformed(evt);
            }
        });

        btnGuardarRegCli.setBackground(new java.awt.Color(79, 157, 157));
        btnGuardarRegCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardarRegCli.setText("GUARDAR");
        btnGuardarRegCli.setMaximumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegCli.setMinimumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegCli.setPreferredSize(new java.awt.Dimension(122, 33));
        btnGuardarRegCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegCliActionPerformed(evt);
            }
        });

        pnlInfCliente.setBackground(new java.awt.Color(79, 157, 157));
        pnlInfCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Cliente"));

        lblPriNomCliente.setText("Primer Nombre *");

        lblCedCliente.setText("Cédula *");

        lblCiuCliente.setText("Ciudad *");

        lblDirCliente.setText("Dirección *");

        lblTelCliente.setText("Teléfono *");

        lblMailCliente.setText("E-Mail *");

        lblGenCliente.setText("Sexo *");

        txtPriNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriNomClienteActionPerformed(evt);
            }
        });
        txtPriNomCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriNomClienteKeyTyped(evt);
            }
        });

        txtCedCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedClienteActionPerformed(evt);
            }
        });
        txtCedCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedClienteKeyTyped(evt);
            }
        });

        txtCiuCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiuClienteKeyTyped(evt);
            }
        });

        txtDirCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirClienteKeyTyped(evt);
            }
        });

        txtTelCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelClienteKeyTyped(evt);
            }
        });

        txtMailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailClienteActionPerformed(evt);
            }
        });
        txtMailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailClienteKeyTyped(evt);
            }
        });

        cboGenCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Femenino", "Masculino" }));
        cboGenCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenClienteActionPerformed(evt);
            }
        });

        lblFecNacCliente.setText("Fecha Nacimiento *");

        lblPriApeCliente.setText("Primer Apellido *");

        lblSegNomCliente.setText("Segundo Nombre");

        lblSegApeCliente.setText("Segundo Apellido");

        txtSegNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegNomClienteActionPerformed(evt);
            }
        });
        txtSegNomCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegNomClienteKeyTyped(evt);
            }
        });

        txtPriApeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriApeClienteActionPerformed(evt);
            }
        });
        txtPriApeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriApeClienteKeyTyped(evt);
            }
        });

        txtSegApeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegApeClienteActionPerformed(evt);
            }
        });
        txtSegApeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegApeClienteKeyTyped(evt);
            }
        });

        lblSegNomModCli1.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout pnlInfClienteLayout = new javax.swing.GroupLayout(pnlInfCliente);
        pnlInfCliente.setLayout(pnlInfClienteLayout);
        pnlInfClienteLayout.setHorizontalGroup(
            pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCedCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(lblCiuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDirCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboGenCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE)
                                    .addComponent(txtCiuCliente))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCedCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfClienteLayout.createSequentialGroup()
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriNomCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPriApeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPriNomCliente)
                            .addComponent(txtPriApeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSegApeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSegApeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecNacCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpFecNacCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addComponent(lblSegNomModCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addComponent(lblSegNomCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSegNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        pnlInfClienteLayout.setVerticalGroup(
            pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSegNomModCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedCliente)
                        .addComponent(txtCedCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriApeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSegApeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPriApeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegApeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboGenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenCliente)
                            .addComponent(lblFecNacCliente))
                        .addGap(11, 11, 11)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelCliente)
                                .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfClienteLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCiuCliente)
                            .addComponent(txtCiuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInfClienteLayout.createSequentialGroup()
                        .addComponent(dtpFecNacCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(pnlInfClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMailCliente)
                            .addComponent(txtMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoRegCli)
                        .addGap(105, 105, 105)
                        .addComponent(lblTitRegCli)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnGuardarRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCancelarRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSalirRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoRegCli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTitRegCli)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRegCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegCliActionPerformed
        // TODO add your handling code here:
        Borrar();
    }//GEN-LAST:event_btnCancelarRegCliActionPerformed

    private void btnSalirRegCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegCliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario clienteJF = new MenuUsuario();
        //clienteJF.setVisible(true);
    }//GEN-LAST:event_btnSalirRegCliActionPerformed

    private void btnGuardarRegCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegCliActionPerformed
        // TODO add your handling code here:
        //int Pregunta;
        //Pregunta = JOptionPane.showConfirmDialog(null,"Desea Modifiacar Los Datos","Pregunta" ,0);
        //if (Pregunta==0)
        //{
        try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn =  mysql.Conectar();

            String sSQL="";
            String Mensaje = "";
            
            String Cedula_C;
            String Nombre_P;
            String Apellido_P;
            String Nombre_S;
            String Apellido_S;
            String Ciudad;
            String Direccion;
            String Telefono;
            String Mail;
            String Genero;
            String Estado;
                        
            Cedula_C = txtCedCliente.getText();
            Nombre_P = txtPriNomCliente.getText();
            Apellido_P = txtPriApeCliente.getText();
            Nombre_S = txtSegNomCliente.getText();
            Apellido_S = txtSegApeCliente.getText();
            Ciudad = txtCiuCliente.getText();
            Direccion = txtDirCliente.getText();
            Telefono = txtTelCliente.getText();
            Mail =  txtMailCliente.getText();
            Genero = cboGenCliente.getSelectedItem().toString(); 
            Estado=cmbEstado.getSelectedItem().toString().substring(0,1); //Obtiene la primera letra del estado
            
            
            
           

            if(Genero.equals("")||Nombre_P.equals("")||Apellido_P.equals("")||Ciudad.equals("")||Direccion.equals("")||Mail.equals("")||Telefono.equals("")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }
            else{
                if(Cedula_C.length()!=10||ValidarNum(Cedula_C)==false||ValidarLetras(Genero)==false||ValidarLetras(Nombre_P)==false
                    ||ValidarLetras(Apellido_P)==false||ValidarLetras(Nombre_S)==false
                    ||ValidarLetras(Apellido_S)==false||ValidarNum(Telefono)==false){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }
                else{
                    try
                    {
                        sSQL = "INSERT INTO cliente(ci_cli, pnom_cli, snom_cli, pape_cli, sape_cli, fec_nac, gen, telf, ciu, dir, mail,estado )" +
                        "value(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                        Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                        PreparedStatement pst = cn.prepareStatement(sSQL);

                        pst.setString(1, Cedula_C);
                        pst.setString(2, Nombre_P);
                        pst.setString(3, Nombre_S);
                        pst.setString(4, Apellido_P);
                        pst.setString(5, Apellido_S);
                        pst.setDate(6, new java.sql.Date(dtpFecNacCliente.getDate().getTime()));
                        pst.setString(7, Genero);
                        pst.setString(8, Telefono);
                        pst.setString(9, Ciudad);
                        pst.setString(10, Direccion);
                        pst.setString(11, Mail);
                        pst.setString(12, Estado);

                        int n = pst.executeUpdate();

                        if (n>0)
                            
                            {
                                JOptionPane.showMessageDialog(null, Mensaje);
                            }

                        }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) 
                        {
                            JOptionPane.showMessageDialog(null, "El Cliente ya esta registrado");
                        }
                    Borrar();
                        
                    }
  
            }
            //Borrar();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //}
        //Borrar();
    }//GEN-LAST:event_btnGuardarRegCliActionPerformed

    private void txtPriNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriNomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriNomClienteActionPerformed

    private void txtCedClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedClienteActionPerformed

    private void txtMailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailClienteActionPerformed

    private void cboGenClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenClienteActionPerformed

    private void txtSegNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegNomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegNomClienteActionPerformed

    private void txtPriApeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriApeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriApeClienteActionPerformed

    private void txtSegApeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegApeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegApeClienteActionPerformed

    private void txtCedClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedClienteKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtCedClienteKeyTyped

    private void txtPriNomClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriNomClienteKeyTyped
        // TODO add your handling code here:
       String texto = txtPriNomCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtPriNomCliente.setText(texto);
        }
    }//GEN-LAST:event_txtPriNomClienteKeyTyped

    private void txtSegNomClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegNomClienteKeyTyped
        // TODO add your handling code here:
        String texto = txtSegNomCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtSegNomCliente.setText(texto);
        }
    }//GEN-LAST:event_txtSegNomClienteKeyTyped

    private void txtPriApeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriApeClienteKeyTyped
        // TODO add your handling code here:
        String texto = txtPriApeCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtPriApeCliente.setText(texto);
        }
        
    }//GEN-LAST:event_txtPriApeClienteKeyTyped

    private void txtSegApeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegApeClienteKeyTyped
        // TODO add your handling code here:
        String texto = txtSegApeCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtSegApeCliente.setText(texto);
        }
    }//GEN-LAST:event_txtSegApeClienteKeyTyped

    private void txtDirClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirClienteKeyTyped
        // TODO add your handling code here:
        String texto = txtDirCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtDirCliente.setText(texto);
        } 
    }//GEN-LAST:event_txtDirClienteKeyTyped

    private void txtTelClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelClienteKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelClienteKeyTyped

    private void txtCiuClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiuClienteKeyTyped
        // TODO add your handling code here:
        String texto = txtCiuCliente.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtCiuCliente.setText(texto);
        } 
    }//GEN-LAST:event_txtCiuClienteKeyTyped

    private void txtMailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailClienteKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isUpperCase(c)){
            String cad = (""+c).toLowerCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_txtMailClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegCli;
    private javax.swing.JButton btnGuardarRegCli;
    private javax.swing.JButton btnSalirRegCli;
    private javax.swing.JComboBox<String> cboGenCliente;
    private javax.swing.JComboBox<String> cmbEstado;
    private com.toedter.calendar.JDateChooser dtpFecNacCliente;
    private javax.swing.JLabel lblCedCliente;
    private javax.swing.JLabel lblCiuCliente;
    private javax.swing.JLabel lblDirCliente;
    private javax.swing.JLabel lblFecNacCliente;
    private javax.swing.JLabel lblGenCliente;
    private javax.swing.JLabel lblIconoRegCli;
    private javax.swing.JLabel lblMailCliente;
    private javax.swing.JLabel lblPriApeCliente;
    private javax.swing.JLabel lblPriNomCliente;
    private javax.swing.JLabel lblSegApeCliente;
    private javax.swing.JLabel lblSegNomCliente;
    private javax.swing.JLabel lblSegNomModCli1;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JLabel lblTitRegCli;
    private javax.swing.JPanel pnlInfCliente;
    private javax.swing.JTextField txtCedCliente;
    private javax.swing.JTextField txtCiuCliente;
    private javax.swing.JTextField txtDirCliente;
    private javax.swing.JTextField txtMailCliente;
    private javax.swing.JTextField txtPriApeCliente;
    private javax.swing.JTextField txtPriNomCliente;
    private javax.swing.JTextField txtSegApeCliente;
    private javax.swing.JTextField txtSegNomCliente;
    private javax.swing.JTextField txtTelCliente;
    // End of variables declaration//GEN-END:variables
}
