package formularios;


import conexion.ConexionMySQL;
import clases.Formatos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class RegEmpleado extends javax.swing.JFrame {
//DefaultComboBoxModel Reg_Emp;
    /**
     * Creates new form RegEmpleado
     */

    public RegEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        
    }
            
    void Borrar()
    {
        txtPriNomEmpleado.setText("");
        txtSegNomEmpleado.setText("");
        txtPriApeEmpleado.setText("");
        txtSegApeEmpleado.setText("");
        txtCedEmpleado.setText("");
        dtpFecNacEmpleado.setDate(null);
        txtCiuEmpleado.setText("");
        txtDirEmpleado.setText("");
        txtTelEmpleado.setText("");
        txtMailEmpleado.setText("");
    }
    
    boolean ValidarLetras(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 64 && palabra.charAt(i) < 91) || (palabra.charAt(i) > 96 && palabra.charAt(i) < 123 )||(palabra.charAt(i) > 163 && palabra.charAt(i) < 166 )))
                return false;
        }
        return true;
    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIconoEmpleado = new javax.swing.JLabel();
        lblTituloEmpleado = new javax.swing.JLabel();
        pnlInfEmpleado = new javax.swing.JPanel();
        lblPriNomEmpleado = new javax.swing.JLabel();
        lblCedEmpleado = new javax.swing.JLabel();
        lblCiuEmpleado = new javax.swing.JLabel();
        lblDirEmpleado = new javax.swing.JLabel();
        lblTelEmpleado = new javax.swing.JLabel();
        lblMailEmpleado = new javax.swing.JLabel();
        lblGenEmpleado = new javax.swing.JLabel();
        txtPriNomEmpleado = new javax.swing.JTextField();
        txtCedEmpleado = new javax.swing.JTextField();
        txtCiuEmpleado = new javax.swing.JTextField();
        txtDirEmpleado = new javax.swing.JTextField();
        txtTelEmpleado = new javax.swing.JTextField();
        txtMailEmpleado = new javax.swing.JTextField();
        cboGenEmpleado = new javax.swing.JComboBox<>();
        dtpFecNacEmpleado = new com.toedter.calendar.JDateChooser();
        lblFecNacEmpleado = new javax.swing.JLabel();
        lblPriApeEmpleado = new javax.swing.JLabel();
        lblSegNomEmpleado = new javax.swing.JLabel();
        lblSegApeEmpleado = new javax.swing.JLabel();
        txtSegNomEmpleado = new javax.swing.JTextField();
        txtPriApeEmpleado = new javax.swing.JTextField();
        txtSegApeEmpleado = new javax.swing.JTextField();
        btnGuaInfPro = new javax.swing.JButton();
        btnCanInfPro = new javax.swing.JButton();
        btnSalInfPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmRegEmpleados"); // NOI18N

        lblIconoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N
        lblIconoEmpleado.setName("frmRegEmpleado"); // NOI18N

        lblTituloEmpleado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloEmpleado.setText("DATOS DEL EMPLEADO");

        pnlInfEmpleado.setBackground(new java.awt.Color(79, 157, 157));
        pnlInfEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Empleado"));

        lblPriNomEmpleado.setText("Primer Nombre *");

        lblCedEmpleado.setText("Cédula *");

        lblCiuEmpleado.setText("Ciudad *");

        lblDirEmpleado.setText("Dirección *");

        lblTelEmpleado.setText("Teléfono *");

        lblMailEmpleado.setText("E-Mail *");

        lblGenEmpleado.setText("Sexo *");

        txtPriNomEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriNomEmpleadoActionPerformed(evt);
            }
        });
        txtPriNomEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriNomEmpleadoKeyTyped(evt);
            }
        });

        txtCedEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedEmpleadoActionPerformed(evt);
            }
        });
        txtCedEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedEmpleadoKeyTyped(evt);
            }
        });

        txtCiuEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiuEmpleadoKeyTyped(evt);
            }
        });

        txtDirEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirEmpleadoKeyTyped(evt);
            }
        });

        txtTelEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelEmpleadoKeyTyped(evt);
            }
        });

        txtMailEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailEmpleadoActionPerformed(evt);
            }
        });
        txtMailEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailEmpleadoKeyTyped(evt);
            }
        });

        cboGenEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Femenino", "Masculino" }));
        cboGenEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenEmpleadoActionPerformed(evt);
            }
        });

        lblFecNacEmpleado.setText("Fecha Nacimiento *");

        lblPriApeEmpleado.setText("Primer Apellido *");

        lblSegNomEmpleado.setText("Segundo Nombre");

        lblSegApeEmpleado.setText("Segundo Apellido");

        txtSegNomEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegNomEmpleadoActionPerformed(evt);
            }
        });
        txtSegNomEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegNomEmpleadoKeyTyped(evt);
            }
        });

        txtPriApeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriApeEmpleadoActionPerformed(evt);
            }
        });
        txtPriApeEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriApeEmpleadoKeyTyped(evt);
            }
        });

        txtSegApeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegApeEmpleadoActionPerformed(evt);
            }
        });
        txtSegApeEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegApeEmpleadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlInfEmpleadoLayout = new javax.swing.GroupLayout(pnlInfEmpleado);
        pnlInfEmpleado.setLayout(pnlInfEmpleadoLayout);
        pnlInfEmpleadoLayout.setHorizontalGroup(
            pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCedEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDirEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(lblCiuEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDirEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboGenEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE)
                                    .addComponent(txtCiuEmpleado))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCedEmpleado)))
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPriNomEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPriApeEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPriApeEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtPriNomEmpleado))))
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSegNomEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSegNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSegApeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSegApeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecNacEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpFecNacEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        pnlInfEmpleadoLayout.setVerticalGroup(
            pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedEmpleado)
                    .addComponent(txtCedEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegNomEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriApeEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSegApeEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPriApeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSegApeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboGenEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenEmpleado)
                            .addComponent(lblFecNacEmpleado))
                        .addGap(11, 11, 11)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelEmpleado)
                                .addComponent(txtTelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCiuEmpleado)
                            .addComponent(txtCiuEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInfEmpleadoLayout.createSequentialGroup()
                        .addComponent(dtpFecNacEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(pnlInfEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMailEmpleado)
                            .addComponent(txtMailEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        btnGuaInfPro.setBackground(new java.awt.Color(79, 157, 157));
        btnGuaInfPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuaInfPro.setText("GUARDAR");
        btnGuaInfPro.setMaximumSize(new java.awt.Dimension(122, 33));
        btnGuaInfPro.setMinimumSize(new java.awt.Dimension(122, 33));
        btnGuaInfPro.setPreferredSize(new java.awt.Dimension(122, 33));
        btnGuaInfPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaInfProActionPerformed(evt);
            }
        });

        btnCanInfPro.setBackground(new java.awt.Color(79, 157, 157));
        btnCanInfPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCanInfPro.setText("CANCELAR");
        btnCanInfPro.setMaximumSize(new java.awt.Dimension(122, 33));
        btnCanInfPro.setMinimumSize(new java.awt.Dimension(122, 33));
        btnCanInfPro.setPreferredSize(new java.awt.Dimension(122, 33));
        btnCanInfPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanInfProActionPerformed(evt);
            }
        });

        btnSalInfPro.setBackground(new java.awt.Color(79, 157, 157));
        btnSalInfPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalInfPro.setText("SALIR");
        btnSalInfPro.setMaximumSize(new java.awt.Dimension(122, 33));
        btnSalInfPro.setMinimumSize(new java.awt.Dimension(122, 33));
        btnSalInfPro.setPreferredSize(new java.awt.Dimension(122, 33));
        btnSalInfPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalInfProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlInfEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIconoEmpleado)
                                .addGap(101, 101, 101)
                                .addComponent(lblTituloEmpleado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnGuaInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCanInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblTituloEmpleado)))
                .addGap(18, 18, 18)
                .addComponent(pnlInfEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuaInfPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pnlInfEmpleado.getAccessibleContext().setAccessibleName("Informacion Empleado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGenEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenEmpleadoActionPerformed

    private void txtCedEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedEmpleadoActionPerformed

    private void btnGuaInfProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaInfProActionPerformed
        // TODO add your handling code here:
        
        try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            String sSQL="";
            String Mensaje="";

            String Cedula_E;
            String Nombre_P;
            String Apellido_P;
            String Nombre_S;
            String Apellido_S;
            String Ciudad;
            String Direccion;
            String Telefono;
            String Mail;
            String Genero;
                        
            Cedula_E = txtCedEmpleado.getText();
            Nombre_P = txtPriNomEmpleado.getText();
            Apellido_P = txtPriApeEmpleado.getText();
            Nombre_S = txtSegNomEmpleado.getText();
            Apellido_S = txtSegApeEmpleado.getText();
            Ciudad = txtCiuEmpleado.getText();
            Direccion = txtDirEmpleado.getText();
            Telefono = txtTelEmpleado.getText();
            Mail =  txtMailEmpleado.getText();
            Genero = cboGenEmpleado.getSelectedItem().toString(); 
           
            
            

            if(Cedula_E.equals("")||Nombre_P.equals("")||Apellido_P.equals("")||Ciudad.equals("")||
                    Direccion.equals("")||Mail.equals("")||Telefono.equals("")||Genero.equals("")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }
            else{
                if(Cedula_E.length()!=10||ValidarNum(Cedula_E)==false||ValidarLetras(Nombre_P)==false||ValidarLetras(Nombre_S)==false
                    ||ValidarLetras(Apellido_P)==false||ValidarLetras(Apellido_S)==false||ValidarLetras(Ciudad)==false||ValidarNum(Telefono)==false
                    ||ValidarLetras(Genero)==false ){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }
                else{
                    
                    try
                    {
                        sSQL = "INSERT INTO empleado(ci_emp, pnom_emp, snom_emp, pape_emp, sape_emp, fec_nac, gen, telf, ciu, dir, mail )" +
                        "value(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                        Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                        PreparedStatement pst = cn.prepareStatement(sSQL);

                        pst.setString(1, Cedula_E);
                        pst.setString(2, Nombre_P);
                        pst.setString(3, Nombre_S);
                        pst.setString(4, Apellido_P);
                        pst.setString(5, Apellido_S);
                        pst.setDate(6, new java.sql.Date(dtpFecNacEmpleado.getDate().getTime()));
                        pst.setString(7, Genero);
                        pst.setString(8, Telefono);
                        pst.setString(9, Ciudad);
                        pst.setString(10, Direccion);
                        pst.setString(11, Mail);

                        int n = pst.executeUpdate();

                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null, Mensaje);
                        }
                        
                    }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) 
                        {
                            JOptionPane.showMessageDialog(null, "El Empleado ya esta registrado");
                            //JOptionPane.showMessageDialog(null, "El código postal no existe o no esta cargado","ADVERTENCIA",JOptionPane.WARNING_MESSAGE)
                        }
                    //Borrar();
                   
                }
            }
            

        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnGuaInfProActionPerformed

    private void btnCanInfProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanInfProActionPerformed
        // TODO add your handling code here:    
        Borrar();
        
    }//GEN-LAST:event_btnCanInfProActionPerformed

    private void btnSalInfProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalInfProActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnSalInfProActionPerformed

    private void txtPriNomEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriNomEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriNomEmpleadoActionPerformed

    private void txtSegNomEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegNomEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegNomEmpleadoActionPerformed

    private void txtPriApeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriApeEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriApeEmpleadoActionPerformed

    private void txtSegApeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegApeEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegApeEmpleadoActionPerformed

    private void txtMailEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailEmpleadoActionPerformed

    private void txtCedEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedEmpleadoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCedEmpleadoKeyTyped

    private void txtPriNomEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriNomEmpleadoKeyTyped
        // TODO add your handling code here:
        String texto = txtPriNomEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtPriNomEmpleado.setText(texto);
        }
        
    }//GEN-LAST:event_txtPriNomEmpleadoKeyTyped

    private void txtSegNomEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegNomEmpleadoKeyTyped
        // TODO add your handling code here:
        String texto = txtSegNomEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtSegNomEmpleado.setText(texto);
        }
         
    }//GEN-LAST:event_txtSegNomEmpleadoKeyTyped

    private void txtPriApeEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriApeEmpleadoKeyTyped
        // TODO add your handling code here:
       String texto = txtPriApeEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtPriApeEmpleado.setText(texto);
        }
    }//GEN-LAST:event_txtPriApeEmpleadoKeyTyped

    private void txtSegApeEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegApeEmpleadoKeyTyped
        // TODO add your handling code here:
         String texto = txtSegApeEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtSegApeEmpleado.setText(texto);
        }
    }//GEN-LAST:event_txtSegApeEmpleadoKeyTyped

    private void txtDirEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirEmpleadoKeyTyped
        // TODO add your handling code here:
      String texto = txtDirEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtDirEmpleado.setText(texto);
        }  
    }//GEN-LAST:event_txtDirEmpleadoKeyTyped

    private void txtTelEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelEmpleadoKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtTelEmpleadoKeyTyped

    private void txtCiuEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiuEmpleadoKeyTyped
        // TODO add your handling code here:
        String texto = txtCiuEmpleado.getText();
        if(texto.length()>0){
            char primeraletra = texto.charAt(0);
            texto = Character.toUpperCase(primeraletra)+texto.substring(1, texto.length());
            txtCiuEmpleado.setText(texto);
        }
        
    }//GEN-LAST:event_txtCiuEmpleadoKeyTyped

    private void txtMailEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailEmpleadoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isUpperCase(c)){
            String cad = (""+c).toLowerCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
         
    }//GEN-LAST:event_txtMailEmpleadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanInfPro;
    private javax.swing.JButton btnGuaInfPro;
    private javax.swing.JButton btnSalInfPro;
    private javax.swing.JComboBox<String> cboGenEmpleado;
    private com.toedter.calendar.JDateChooser dtpFecNacEmpleado;
    private javax.swing.JLabel lblCedEmpleado;
    private javax.swing.JLabel lblCiuEmpleado;
    private javax.swing.JLabel lblDirEmpleado;
    private javax.swing.JLabel lblFecNacEmpleado;
    private javax.swing.JLabel lblGenEmpleado;
    private javax.swing.JLabel lblIconoEmpleado;
    private javax.swing.JLabel lblMailEmpleado;
    private javax.swing.JLabel lblPriApeEmpleado;
    private javax.swing.JLabel lblPriNomEmpleado;
    private javax.swing.JLabel lblSegApeEmpleado;
    private javax.swing.JLabel lblSegNomEmpleado;
    private javax.swing.JLabel lblTelEmpleado;
    private javax.swing.JLabel lblTituloEmpleado;
    private javax.swing.JPanel pnlInfEmpleado;
    private javax.swing.JTextField txtCedEmpleado;
    private javax.swing.JTextField txtCiuEmpleado;
    private javax.swing.JTextField txtDirEmpleado;
    private javax.swing.JTextField txtMailEmpleado;
    private javax.swing.JTextField txtPriApeEmpleado;
    private javax.swing.JTextField txtPriNomEmpleado;
    private javax.swing.JTextField txtSegApeEmpleado;
    private javax.swing.JTextField txtSegNomEmpleado;
    private javax.swing.JTextField txtTelEmpleado;
    // End of variables declaration//GEN-END:variables
}
