package formularios;


import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class RegProAseguradora extends javax.swing.JFrame {
DefaultComboBoxModel proforma;
    /**
     * Creates new form RegProAseguradora
     */
    public RegProAseguradora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        cargar();
        txtCodRegProAse.setVisible(false);
        cboNomRegProAse.setEditable(true); //para poder escribir adentro
        AutoCompleteDecorator.decorate(this.cboNomRegProAse);
    }
    void cargar()
    {
        try
        {
            String Nombre;

            String sSQL="";

            proforma = new DefaultComboBoxModel();

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
   
            sSQL = "SELECT nom_emp FROM aseguradora";

            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Nombre = rs.getString("nom_emp");
                proforma.addElement(Nombre);
            }
            cboNomRegProAse.setModel(proforma);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);

        }
    }



    void CargarCodigo(String Codigo)
    {
        try
        {
            String sSQL = "";
            String Guardar = "";

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT cod_emp FROM aseguradora " + "WHERE CONCAT(nom_emp) LIKE '%"+Codigo+"%'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                Guardar = rs.getString("cod_emp");

            }
            txtCodRegProAse.setText(Guardar);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void borrar()
    {
        txtCodProRegProAse.setText("");
        txtRegPorRoboProAse.setText("");
        txtRegPorAccAse.setText("");
        txtPorMedRegProAse.setText("");
        cboRoboRegProAse.setSelectedItem("Seleccione");
        cboAccRegProAse.setSelectedItem("Seleccione");
        cboMedRegProAse.setSelectedItem("Seleccione");
        cboAntRegProAse.setSelectedItem("Seleccione");
        cboResRegProAse.setSelectedItem("Seleccione");
       
    }
        
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 47 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitRegProAse = new javax.swing.JLabel();
        lblIconoRegProAse = new javax.swing.JLabel();
        pnlNomRegProAse = new javax.swing.JPanel();
        cboNomRegProAse = new javax.swing.JComboBox();
        pnlDatRegProAse = new javax.swing.JPanel();
        lblTipRegProAse = new javax.swing.JLabel();
        cboAntRegProAse = new javax.swing.JComboBox();
        lblRoboRegProAse = new javax.swing.JLabel();
        lblAccRegProAse = new javax.swing.JLabel();
        lblMedRegProAse = new javax.swing.JLabel();
        cboRoboRegProAse = new javax.swing.JComboBox();
        cboAccRegProAse = new javax.swing.JComboBox();
        cboMedRegProAse = new javax.swing.JComboBox();
        lblPorMedRegProAse = new javax.swing.JLabel();
        txtPorMedRegProAse = new javax.swing.JTextField();
        lblRegPorAccAse = new javax.swing.JLabel();
        txtRegPorAccAse = new javax.swing.JTextField();
        lblRegPorRoboProAse = new javax.swing.JLabel();
        txtRegPorRoboProAse = new javax.swing.JTextField();
        lblCodRegProAse = new javax.swing.JLabel();
        txtCodProRegProAse = new javax.swing.JTextField();
        lblTipRegProAse1 = new javax.swing.JLabel();
        cboResRegProAse = new javax.swing.JComboBox();
        btnGuardarRegProAse = new javax.swing.JButton();
        btnCancelarRegProAse = new javax.swing.JButton();
        btnSalirRegProAse = new javax.swing.JButton();
        txtCodRegProAse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");

        lblTitRegProAse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitRegProAse.setText("COBERTURA GENERAL DE LA ASEGURADORA");

        lblIconoRegProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoProforma.jpg"))); // NOI18N

        pnlNomRegProAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlNomRegProAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre De La Empresa"));

        cboNomRegProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomRegProAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNomRegProAseLayout = new javax.swing.GroupLayout(pnlNomRegProAse);
        pnlNomRegProAse.setLayout(pnlNomRegProAseLayout);
        pnlNomRegProAseLayout.setHorizontalGroup(
            pnlNomRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomRegProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNomRegProAse, 0, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNomRegProAseLayout.setVerticalGroup(
            pnlNomRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomRegProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNomRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatRegProAse.setBackground(new java.awt.Color(79, 157, 157));
        pnlDatRegProAse.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Que Ofrece Aseguradora"));

        lblTipRegProAse.setText("Antiguedad del Vehículo *");

        cboAntRegProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Hasta 10 años de fabricación", "Hasta 12 años de fabricación", "Hasta 13 años de fabricación", "Hasta 14 años de fabricación", "Hasta 15 años de fabricación" }));

        lblRoboRegProAse.setText("Pérdida Por Robo *");

        lblAccRegProAse.setText("Pérdida Por Accidente *");

        lblMedRegProAse.setText("Gatos Médicos *");

        cboRoboRegProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        cboAccRegProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        cboMedRegProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "TOTAL", "PARCIAL" }));

        lblPorMedRegProAse.setText("Porcentaje de Cobertura *       %");

        lblRegPorAccAse.setText("Porcentaje de Cobertura *       %");

        lblRegPorRoboProAse.setText("Porcentaje de Cobertura *       %");

        lblCodRegProAse.setText("Código de Cobertura*");

        lblTipRegProAse1.setText("Responsabilidad Civil *");

        cboResRegProAse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "En Ecuador", "No aplica fuera del Ecuador", "Dentro de territorio ecuatoriano", "Aplica dentro de Comunidad Andina" }));

        javax.swing.GroupLayout pnlDatRegProAseLayout = new javax.swing.GroupLayout(pnlDatRegProAse);
        pnlDatRegProAse.setLayout(pnlDatRegProAseLayout);
        pnlDatRegProAseLayout.setHorizontalGroup(
            pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatRegProAseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccRegProAse)
                    .addComponent(lblRoboRegProAse)
                    .addComponent(lblTipRegProAse)
                    .addComponent(lblMedRegProAse)
                    .addComponent(lblCodRegProAse)
                    .addComponent(lblTipRegProAse1))
                .addGap(33, 33, 33)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboResRegProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAccRegProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMedRegProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAntRegProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboRoboRegProAse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodProRegProAse))
                .addGap(47, 47, 47)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRegPorAccAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegPorRoboProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPorMedRegProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorMedRegProAse, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtRegPorRoboProAse)
                    .addComponent(txtRegPorAccAse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatRegProAseLayout.setVerticalGroup(
            pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatRegProAseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodRegProAse)
                    .addComponent(txtCodProRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPorMedRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRoboRegProAse)
                        .addComponent(cboRoboRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegPorRoboProAse)))
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatRegProAseLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccRegProAse)
                            .addComponent(cboAccRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegPorAccAse)))
                    .addGroup(pnlDatRegProAseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRegPorRoboProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMedRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedRegProAse)
                    .addComponent(lblPorMedRegProAse)
                    .addComponent(txtRegPorAccAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAntRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipRegProAse))
                .addGap(20, 20, 20)
                .addGroup(pnlDatRegProAseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboResRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipRegProAse1))
                .addGap(15, 15, 15))
        );

        btnGuardarRegProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnGuardarRegProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardarRegProAse.setText("GUARDAR");
        btnGuardarRegProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnGuardarRegProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnGuardarRegProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegProAseActionPerformed(evt);
            }
        });

        btnCancelarRegProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnCancelarRegProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelarRegProAse.setText("CANCELAR");
        btnCancelarRegProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnCancelarRegProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnCancelarRegProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegProAseActionPerformed(evt);
            }
        });

        btnSalirRegProAse.setBackground(new java.awt.Color(79, 157, 157));
        btnSalirRegProAse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalirRegProAse.setText("SALIR");
        btnSalirRegProAse.setMaximumSize(new java.awt.Dimension(122, 33));
        btnSalirRegProAse.setMinimumSize(new java.awt.Dimension(122, 33));
        btnSalirRegProAse.setPreferredSize(new java.awt.Dimension(122, 33));
        btnSalirRegProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegProAseActionPerformed(evt);
            }
        });

        txtCodRegProAse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRegProAseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIconoRegProAse)
                        .addGap(37, 37, 37)
                        .addComponent(lblTitRegProAse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlNomRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnGuardarRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCancelarRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSalirRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDatRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoRegProAse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTitRegProAse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNomRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(pnlDatRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRegProAse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalirRegProAse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNomRegProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomRegProAseActionPerformed
        // TODO add your handling code here:
        String Codigo = cboNomRegProAse.getSelectedItem().toString();
        CargarCodigo(Codigo);
    }//GEN-LAST:event_cboNomRegProAseActionPerformed

    private void btnGuardarRegProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegProAseActionPerformed
        // TODO add your handling code here:
        try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            String sSQL=("");
            String Mensaje=("");

            String Nombre_Emp;
            String Robo;
            String Acci;
            String Medi;
            String Cod_Pro;
            String Por_Robo;
            String Por_Acci;
            String Por_Medi;
            String Ant_v;
            String Res_v;
            String Cod_Emp;

            Nombre_Emp = cboNomRegProAse.getSelectedItem().toString();
            Robo = cboRoboRegProAse.getSelectedItem().toString();
            Acci = cboAccRegProAse.getSelectedItem().toString();
            Medi = cboMedRegProAse.getSelectedItem().toString();
            Cod_Pro = txtCodProRegProAse.getText();
            Por_Robo = txtRegPorRoboProAse.getText();
            Por_Acci = txtRegPorAccAse.getText();
            Por_Medi = txtPorMedRegProAse.getText();
            Ant_v = cboAntRegProAse.getSelectedItem().toString();
            Res_v = cboResRegProAse.getSelectedItem().toString();
            Cod_Emp = txtCodRegProAse.getText();

            if(Robo.equals("Seleccione")||Acci.equals("Seleccione")||
                Medi.equals("Seleccione")||Cod_Pro.equals("")||Por_Robo.equals("Seleccione")||Por_Acci.equals("Seleccione")||
                Por_Medi.equals("Seleccione")||Ant_v.equals("Seleccione")||Res_v.equals("Seleccione")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }

            else{
                if(ValidarNum(Cod_Pro)==false||ValidarNum(Por_Robo)==false||ValidarNum(Por_Acci)==false||ValidarNum(Por_Medi)==false){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }

                else{
                    sSQL = "INSERT INTO proforma(nom_emp, robo, accidente, medico, cod_pro, por_robo, por_acci, por_med, ant_veh, res_civ, cod_emp)" +
                    "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                    Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                    PreparedStatement pst = cn.prepareStatement(sSQL);

                    pst.setString(1, Nombre_Emp);
                    pst.setString(2, Robo);
                    pst.setString(3, Acci);
                    pst.setString(4, Medi);
                    pst.setString(5, Cod_Pro);
                    pst.setString(6, Por_Robo);
                    pst.setString(7, Por_Acci);
                    pst.setString(8, Por_Medi);
                    pst.setString(9, Ant_v);
                    pst.setString(10, Res_v);
                    pst.setString(11, Cod_Emp);

                    int n = pst.executeUpdate();

                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null, Mensaje);
                    }
                    borrar();
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnGuardarRegProAseActionPerformed

    private void btnCancelarRegProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegProAseActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_btnCancelarRegProAseActionPerformed

    private void btnSalirRegProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegProAseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirRegProAseActionPerformed

    private void txtCodRegProAseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRegProAseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRegProAseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegProAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegProAseguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRegProAse;
    private javax.swing.JButton btnGuardarRegProAse;
    private javax.swing.JButton btnSalirRegProAse;
    private javax.swing.JComboBox cboAccRegProAse;
    private javax.swing.JComboBox cboAntRegProAse;
    private javax.swing.JComboBox cboMedRegProAse;
    private javax.swing.JComboBox cboNomRegProAse;
    private javax.swing.JComboBox cboResRegProAse;
    private javax.swing.JComboBox cboRoboRegProAse;
    private javax.swing.JLabel lblAccRegProAse;
    private javax.swing.JLabel lblCodRegProAse;
    private javax.swing.JLabel lblIconoRegProAse;
    private javax.swing.JLabel lblMedRegProAse;
    private javax.swing.JLabel lblPorMedRegProAse;
    private javax.swing.JLabel lblRegPorAccAse;
    private javax.swing.JLabel lblRegPorRoboProAse;
    private javax.swing.JLabel lblRoboRegProAse;
    private javax.swing.JLabel lblTipRegProAse;
    private javax.swing.JLabel lblTipRegProAse1;
    private javax.swing.JLabel lblTitRegProAse;
    private javax.swing.JPanel pnlDatRegProAse;
    private javax.swing.JPanel pnlNomRegProAse;
    private javax.swing.JTextField txtCodProRegProAse;
    private javax.swing.JTextField txtCodRegProAse;
    private javax.swing.JTextField txtPorMedRegProAse;
    private javax.swing.JTextField txtRegPorAccAse;
    private javax.swing.JTextField txtRegPorRoboProAse;
    // End of variables declaration//GEN-END:variables
}
