package formularios;




import conexion.ConexionMySQL;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Richard
 */
public class RegUsuario extends javax.swing.JFrame {
DefaultTableModel modelo;
DefaultComboBoxModel Ced_Emp;
    /**
     * Creates new form Login
     */
    public RegUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(79,157,157));
        Cargar_Nombre();
        tblUsuario.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
    
         @Override
         public void valueChanged(ListSelectionEvent e){
             if(tblUsuario.getSelectedRow() != -1)
         {
             
            int fila = tblUsuario.getSelectedRow();
            cboCedLogEmp.setSelectedItem(tblUsuario.getValueAt(fila, 0));
            txtNickLogEmp.setText(tblUsuario.getValueAt(fila, 1).toString());
            txtPassLogEmp.setText(tblUsuario.getValueAt(fila, 2).toString());
            cboTipLogEmp.setSelectedItem(tblUsuario.getValueAt(fila, 3)); 
            
                
     }
    }
    });
       
    }
    void Borrar()
    {
      
        txtNickLogEmp.setText("");
        txtPassLogEmp.setText("");
        cboTipLogEmp.setSelectedItem("Seleccione");
        cboCedLogEmp.setSelectedItem("Seleccione");
    }
    void Cargar_Nombre()
    {
        try
        {
            String Nombre_Propietario;
            String sSQL="";

            Ced_Emp = new DefaultComboBoxModel();
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT ci_emp FROM empleado";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while (rs.next())
            {
                Nombre_Propietario = rs.getString("ci_emp");
                Ced_Emp.addElement(Nombre_Propietario);
            }
            cboCedLogEmp.setModel(Ced_Emp);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void CargarTabla(String Informacion)
    {
        try
        {
            String sSQL="";
            String[] Titulos = {"EMPLEADO","USUARIO","CONTRASEÑA","TIPO USUARIO"};
            String[] Datos = new String[7];

            modelo = new DefaultTableModel(null,Titulos);

            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            sSQL = "SELECT ci_emp, nick, password , tipo_usuario   FROM usuario "
                    + "WHERE CONCAT(ci_emp) LIKE '%"+Informacion+"%'";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);

            while(rs.next())
            {
                        Datos[0]=rs.getString("ci_emp");
                        Datos[1]=rs.getString("nick");
                        Datos[2]=rs.getString("password");
                        Datos[3]=rs.getString("tipo_usuario");
                        
                         modelo.addRow(Datos);

            }
            tblUsuario.setModel(modelo);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    boolean ValidarLetras(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 64 && palabra.charAt(i) < 91) || (palabra.charAt(i) > 96 && palabra.charAt(i) < 123)))
                return false;
        }
        return true;
    }
    
    boolean ValidarNum(String palabra){
        for(int i = 0; i < palabra.length(); i++){
            if(!((palabra.charAt(i) > 43 && palabra.charAt(i) < 58)))
                return false;
        }
        return true;
    } 
   
    

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogEmp = new javax.swing.JPanel();
        lblNickLogEmp = new javax.swing.JLabel();
        lblPassLogEmp = new javax.swing.JLabel();
        lblTipLogEmp = new javax.swing.JLabel();
        txtNickLogEmp = new javax.swing.JTextField();
        cboTipLogEmp = new javax.swing.JComboBox();
        txtPassLogEmp = new javax.swing.JPasswordField();
        scpLogEmp = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        lblTitLogEmp = new javax.swing.JLabel();
        btnGuaLogEmp = new javax.swing.JButton();
        pnlCedLogEmp = new javax.swing.JPanel();
        cboCedLogEmp = new javax.swing.JComboBox();
        lblIconoLogEmp = new javax.swing.JLabel();
        btnEliUsu = new javax.swing.JButton();
        btnSalEliPro = new javax.swing.JButton();
        btnMosModPro = new javax.swing.JButton();
        btnModModEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVENDAÑO AGENCIA DE SEGUROS");
        setName("frmLogin"); // NOI18N

        pnlLogEmp.setBackground(new java.awt.Color(79, 157, 157));
        pnlLogEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));

        lblNickLogEmp.setText("Usuario *");

        lblPassLogEmp.setText("Contraseña *");

        lblTipLogEmp.setText("Tipo de Usuario *");

        cboTipLogEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Administrador", "Agente", "Secretaria" }));
        cboTipLogEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboTipLogEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipLogEmpActionPerformed(evt);
            }
        });

        txtPassLogEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassLogEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogEmpLayout = new javax.swing.GroupLayout(pnlLogEmp);
        pnlLogEmp.setLayout(pnlLogEmpLayout);
        pnlLogEmpLayout.setHorizontalGroup(
            pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNickLogEmp)
                    .addComponent(lblPassLogEmp)
                    .addComponent(lblTipLogEmp))
                .addGap(27, 27, 27)
                .addGroup(pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassLogEmp)
                    .addComponent(txtNickLogEmp)
                    .addComponent(cboTipLogEmp, 0, 117, Short.MAX_VALUE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        pnlLogEmpLayout.setVerticalGroup(
            pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogEmpLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNickLogEmp)
                    .addComponent(txtNickLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassLogEmp)
                    .addComponent(txtPassLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipLogEmp)
                    .addComponent(cboTipLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpLogEmp.setViewportView(tblUsuario);

        lblTitLogEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitLogEmp.setText("LISTA DE USUARIOS");

        btnGuaLogEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnGuaLogEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuaLogEmp.setText("GUARDAR");
        btnGuaLogEmp.setToolTipText("");
        btnGuaLogEmp.setMaximumSize(new java.awt.Dimension(147, 33));
        btnGuaLogEmp.setMinimumSize(new java.awt.Dimension(147, 33));
        btnGuaLogEmp.setPreferredSize(new java.awt.Dimension(147, 33));
        btnGuaLogEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaLogEmpActionPerformed(evt);
            }
        });

        pnlCedLogEmp.setBackground(new java.awt.Color(79, 157, 157));
        pnlCedLogEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Cédula Empleado"));

        cboCedLogEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cboCedLogEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCedLogEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCedLogEmpLayout = new javax.swing.GroupLayout(pnlCedLogEmp);
        pnlCedLogEmp.setLayout(pnlCedLogEmpLayout);
        pnlCedLogEmpLayout.setHorizontalGroup(
            pnlCedLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCedLogEmpLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cboCedLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlCedLogEmpLayout.setVerticalGroup(
            pnlCedLogEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCedLogEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboCedLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblIconoLogEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N

        btnEliUsu.setBackground(new java.awt.Color(79, 157, 157));
        btnEliUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btnEliUsu.setText("ELIMINAR");
        btnEliUsu.setMaximumSize(new java.awt.Dimension(147, 33));
        btnEliUsu.setMinimumSize(new java.awt.Dimension(147, 33));
        btnEliUsu.setPreferredSize(new java.awt.Dimension(147, 33));
        btnEliUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliUsuActionPerformed(evt);
            }
        });

        btnSalEliPro.setBackground(new java.awt.Color(79, 157, 157));
        btnSalEliPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btnSalEliPro.setText("SALIR");
        btnSalEliPro.setMaximumSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.setMinimumSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.setPreferredSize(new java.awt.Dimension(147, 33));
        btnSalEliPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalEliProActionPerformed(evt);
            }
        });

        btnMosModPro.setBackground(new java.awt.Color(79, 157, 157));
        btnMosModPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnMosModPro.setText("MOSTRAR DATOS");
        btnMosModPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMosModProActionPerformed(evt);
            }
        });

        btnModModEmp.setBackground(new java.awt.Color(79, 157, 157));
        btnModModEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnModModEmp.setText("MODIFICAR");
        btnModModEmp.setMaximumSize(new java.awt.Dimension(122, 33));
        btnModModEmp.setMinimumSize(new java.awt.Dimension(122, 33));
        btnModModEmp.setPreferredSize(new java.awt.Dimension(122, 33));
        btnModModEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModModEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(scpLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCedLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblTitLogEmp)))
                        .addGap(119, 119, 119)
                        .addComponent(lblIconoLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnGuaLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModModEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMosModPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitLogEmp)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCedLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblIconoLogEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scpLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuaLogEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMosModPro)
                    .addComponent(btnSalEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModModEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipLogEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipLogEmpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTipLogEmpActionPerformed

    private void btnGuaLogEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaLogEmpActionPerformed
        // TODO add your handling code here:
        //String ins="INSERT INTO usuario (nick, password,tipo_usuario) VALUES(?,?,?)";
         try
        {
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();

            String sSQL="";
            String Mensaje="";

            String Propietario;
            String Nick_E;
            String Pass;
            String Tipo;
            

            Propietario = cboCedLogEmp.getSelectedItem().toString();
            Nick_E = txtNickLogEmp.getText();
            Pass = new String (txtPassLogEmp.getPassword());
            Tipo = cboTipLogEmp.getSelectedItem().toString();
            
            if(Tipo.equals("")||Pass.equals("")||Nick_E.equals("")){
                JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
            }
            else{
                if(ValidarLetras(Tipo)==false||ValidarLetras(Nick_E)==false){
                    JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta");
                }
                else{
                    try
                    {

                        sSQL = "INSERT INTO usuario(ci_emp, nick, password, tipo_usuario)" +
                        "value(?, ?, ?, ?)";

                        Mensaje ="DATOS GUARDADOS DE FORMA CORRECTA";

                        PreparedStatement pst = cn.prepareStatement(sSQL);

                        pst.setString(1, Propietario);
                        pst.setString(2, Nick_E);
                        pst.setString(3, Pass);
                        pst.setString(4, Tipo);
                        
                        int n = pst.executeUpdate();

                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null, Mensaje);
                            String Informacion = lblIconoLogEmp.getText();
                            CargarTabla(Informacion);

                        }
                    }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) 
                    {
                       JOptionPane.showMessageDialog(null, "El empleado ya tiene registrado usuario");
                    }

                    Borrar();
                }
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
         Borrar();
 
    }//GEN-LAST:event_btnGuaLogEmpActionPerformed

    private void cboCedLogEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCedLogEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCedLogEmpActionPerformed

    private void txtPassLogEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassLogEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassLogEmpActionPerformed

    private void btnEliUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliUsuActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        int fila= tblUsuario.getSelectedRow();
        if(fila<0)
            {
             JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
            }
        else
        {
            int Pregunta;
            Pregunta = JOptionPane.showConfirmDialog(null,"Desea Eliminar Los Datos","Pregunta" ,0);
            if (Pregunta==0)
            {
                idfila= tblUsuario.getValueAt(fila, 0).toString();
                String eli="DELETE FROM usuario WHERE ci_emp = '"+idfila+"'";
                PreparedStatement pst;
                try
                {
                    pst = cn.prepareStatement(eli);
                    int m=pst.executeUpdate();
                    if(m>0)
                    {
                        JOptionPane.showMessageDialog(this, "ELIMINO LOS DATOS DE FORMA CORRECTA");
                        String Informacion = lblIconoLogEmp.getText();
                        CargarTabla(Informacion);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                        String Informacion = lblIconoLogEmp.getText();
                        CargarTabla(Informacion);
                    }
                
                } catch (SQLException ex) 
                {
                    Logger.getLogger(EliProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEliUsuActionPerformed

    private void btnSalEliProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalEliProActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MenuUsuario MenuUsuarioJF = new MenuUsuario();
        //MenuUsuarioJF.setVisible(true);
    }//GEN-LAST:event_btnSalEliProActionPerformed

    private void btnMosModProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMosModProActionPerformed
        // TODO add your handling code here:
        String Informacion = lblIconoLogEmp.getText();
        CargarTabla(Informacion);
    }//GEN-LAST:event_btnMosModProActionPerformed

    private void btnModModEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModModEmpActionPerformed
        // TODO add your handling code here:        
       
        int Pregunta;
        Pregunta = JOptionPane.showConfirmDialog(null,"Desea Modifiacar Los Datos","Pregunta" ,0);
        if (Pregunta==0)
        {
            try
            {
                String sSQL="";
                String Mensaje="";
                

                String Propietario = cboCedLogEmp.getSelectedItem().toString();
                String Nick_E = txtNickLogEmp.getText();
                String Pass = new String (txtPassLogEmp.getPassword());
                String Tipo = cboTipLogEmp.getSelectedItem().toString();
                
                
                ConexionMySQL mysql = new ConexionMySQL();
                Connection cn = mysql.Conectar();
                
                 if(Nick_E.equals("")||Pass.equals("")||Tipo.equals("")){
                    JOptionPane.showMessageDialog(null, "Llene todos los campos requeridos");
                }

                else{
                    if(ValidarLetras(Tipo)==false||ValidarLetras(Nick_E)==false){
                        JOptionPane.showMessageDialog(null, "Campos llenos de manera incorrecta----");
                    }

                    else{

                sSQL = "UPDATE usuario SET nick = '"+Nick_E+"', password = '"+Pass+"', tipo_usuario = '"+Tipo+"'";
                sSQL = sSQL+ "WHERE ci_emp = '"+Propietario+"'";
                
                Mensaje ="DATOS MODIFICADOS DE FORMA CORRECTA";
                
                Statement st = cn.createStatement();
                int n = st.executeUpdate(sSQL);
                
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null, Mensaje);
                    }
                    String Informacion = lblIconoLogEmp.getText();
                    CargarTabla(Informacion);
                    Borrar();
                    
                    }
                 }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnModModEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliUsu;
    private javax.swing.JButton btnGuaLogEmp;
    private javax.swing.JButton btnModModEmp;
    private javax.swing.JButton btnMosModPro;
    private javax.swing.JButton btnSalEliPro;
    private javax.swing.JComboBox cboCedLogEmp;
    private javax.swing.JComboBox cboTipLogEmp;
    private javax.swing.JLabel lblIconoLogEmp;
    private javax.swing.JLabel lblNickLogEmp;
    private javax.swing.JLabel lblPassLogEmp;
    private javax.swing.JLabel lblTipLogEmp;
    private javax.swing.JLabel lblTitLogEmp;
    private javax.swing.JPanel pnlCedLogEmp;
    private javax.swing.JPanel pnlLogEmp;
    private javax.swing.JScrollPane scpLogEmp;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtNickLogEmp;
    private javax.swing.JPasswordField txtPassLogEmp;
    // End of variables declaration//GEN-END:variables
String idfila="";
}
